Repository JoinColony/colonyNetwork, pull requests merged in 2018-11, with the labels that each got.

#412 Enable contract error messages on mining client
  helpers/test-helper.js
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/package.json
  test/colony-network-mining.js
  yarn.lock
Labels: maintenance

#431 Greenkeeper/prettier 1.15.2
  package.json
  scripts/check-recovery.js
  yarn.lock
Labels: greenkeeper

#399 Miner variable rewards I
  contracts/ColonyFunding.sol
  contracts/ColonyNetworkMining.sol
  contracts/IColonyNetwork.sol
  contracts/IReputationMiningCycle.sol
  contracts/ITokenLocking.sol
  contracts/ReputationMiningCycle.sol
  contracts/TokenLocking.sol
  contracts/TokenLockingStorage.sol
  test/colony-network-mining.js
  test/token-locking.js
Labels: under-review

#436 Rename Colony owner role to founder
  contracts/Colony.sol
  contracts/ColonyAuthority.sol
  contracts/ColonyNetwork.sol
  contracts/ColonyStorage.sol
  contracts/ContractRecovery.sol
  contracts/IColony.sol
  contracts/IColonyNetwork.sol
  contracts/IRecovery.sol
  scripts/generate-test-contracts.sh
  test/colony-network-recovery.js
  test/colony-network.js
  test/colony-recovery.js
  test/colony.js
  test/meta-colony.js
  upgrade-test/colony-upgrade.js
Labels: under-review

#435 Upgrades truffle to beta.2 version
  gasCosts/gasCosts.js
  helpers/constants.js
  helpers/test-data-generator.js
  helpers/test-helper.js
  migrations/2_deploy_contracts.js
  package.json
  packages/reputation-miner/package.json
  test/colony-funding.js
  test/colony-network-auction.js
  test/colony-network-mining.js
  test/colony-network-recovery.js
  test/colony-network.js
  test/colony-recovery.js
  test/colony-task.js
  test/colony.js
  test/meta-colony.js
  test/reputation-update.js
  test/token-locking.js
  upgrade-test/colony-upgrade.js
  yarn.lock
Labels: maintenance

#445 Downgrade truffle to 5.0.0.beta.1
  .soliumignore
  gasCosts/gasCosts.js
  package.json
  packages/reputation-miner/package.json
  test/colony-funding.js
  test/colony-network-auction.js
  test/colony-network-mining.js
  test/colony-network-recovery.js
  test/token-locking.js
  yarn.lock
Labels: maintenance

#441 Big Old Test Refactor 1
  contracts/ReputationMiningCycle.sol
  helpers/constants.js
  helpers/test-data-generator.js
  helpers/test-helper.js
  test/colony-funding.js
  test/colony-network-auction.js
  test/colony-network-mining.js
  test/colony-network-recovery.js
  test/colony-task.js
  test/colony.js
  test/meta-colony.js
  test/reputation-update.js
  test/token-locking.js
Labels: under-review

#450 Expose `ColonyAuthority.hasUserRole` on `Colony`
  contracts/Colony.sol
  contracts/IColony.sol
  test/colony.js
  upgrade-test/colony-upgrade.js
Labels: feature
