Repository JoinColony/colonyNetwork, pull requests merged in 2018-09, with the labels that each got.

#331 Update solidity coverage to 0.5.11 and changes for lockfile update issues
  .circleci/config.yml
  package.json
  yarn.lock
Labels: maintenance, ready-for-review

#332 Update contract loader for second Rinkeby contract deployment
  packages/colony-js-contract-loader-network/config.json
  packages/colony-js-contract-loader-network/contracts/static/EtherRouter.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v2/Authority.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v2/IColony.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v2/IColonyNetwork.json
  packages/colony-js-contract-loader-network/package.json
  packages/colony-js-contract-loader-network/src/NetworkLoader.js
  packages/colony-js-contract-loader-network/src/__tests__/NetworkLoader.test.js
Labels: maintenance, ready-for-review

#334 Use correct Rinkeby colonyNetwork address
  packages/colony-js-contract-loader-network/contracts/static/EtherRouter.json
  packages/colony-js-contract-loader-network/package.json
Labels: bug

#336 Update Rinkeby ABIs
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v2/Authority.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v2/IColony.json
  packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v2/IColonyNetwork.json
  packages/colony-js-contract-loader-network/package.json
Labels: bug

#330 Make the due date default to 90 days in future
  contracts/ColonyTask.sol
  test/colony-task-work-rating.js
  test/colony.js
  upgrade-test/colony-upgrade.js
Labels: under-review

#342 Remove obsolete todos
  contracts/ColonyFunding.sol
  contracts/ReputationMiningCycle.sol
  contracts/ReputationMiningCycleRespond.sol
  contracts/ReputationMiningCycleStorage.sol
  gasCosts/gasCosts.js
  packages/reputation-miner/ReputationMiner.js
  test/meta-colony.js
Labels: in-progress, maintenance

#357 Allow reputation oracle to return historical proofs
  .circleci/config.yml
  package.json
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/ReputationMinerClient.js
  test/colony-network-mining.js
  yarn.lock
Labels: feature

#358 Update eslint-config-prettier to version 3.0.1
  package.json
  yarn.lock
Labels: maintenance

#293 Fix TODOs for reputation mining submission windows
  contracts/ReputationMiningCycle.sol
  gasCosts/gasCosts.js
  helpers/test-helper.js
  packages/reputation-miner/ReputationMiner.js
  test/colony-network-mining.js
Labels: under-review

#359 Add ENS bits required by DDB team
  contracts/Authority.sol
  contracts/Colony.sol
  contracts/ColonyNetwork.sol
  contracts/ColonyNetworkENS.sol
  contracts/ColonyNetworkRegistrar.sol
  contracts/ColonyNetworkStorage.sol
  contracts/IColony.sol
  contracts/IColonyNetwork.sol
  contracts/TokenLocking.sol
  helpers/upgradable-contracts.js
  migrations/2_deploy_contracts.js
  migrations/3_setup_colony_network.js
  scripts/check-recovery.js
  test/colony-network.js
  test/meta-colony.js
  test/reputation-update.js
Labels: feature, in-progress

#361 Amend 'ratings' description in docs
  docs/_Docs_Tasks.md
Labels: documentation

#363 Remove GreenKeeper config from CI
  .circleci/config.yml
Labels: maintenance
