Repository JoinColony/colonyNetwork, pull requests merged in 2018-08, with the labels that each got.

#298 Updated Solium to 1.1.8
  .soliumrc.json
  contracts/EtherRouter.sol
  contracts/ReputationMiningCycle.sol
  package.json
  yarn.lock
Labels: maintenance

#300 Change contributing docs with updates to milestone
  docs/CONTRIBUTING.md
Labels: maintenance

#288 Upgrade to Truffle v5
  .circleci/config.yml
  .solcover.js
  contracts/ColonyStorage.sol
  gasCosts/gasCosts.js
  helpers/constants.js
  helpers/test-data-generator.js
  helpers/test-helper.js
  helpers/upgradable-contracts.js
  migrations/2_deploy_contracts.js
  migrations/4_setup_colony_version_resolver.js
  migrations/5_setup_token_locking.js
  migrations/6_setup_meta_colony.js
  migrations/7_setup_ens_registry.js
  package.json
  parity-genesis.template.json
  scripts/start-blockchain-client.sh
  test/colony-funding.js
  test/colony-network-auction.js
  test/colony-network-mining.js
  test/colony-network.js
  test/colony-task-work-rating.js
  test/colony.js
  test/meta-colony.js
  test/reputation-update.js
  test/router-resolver.js
  test/token-locking.js
  truffle.js
  upgrade-test/colony-network-upgrade.js
  upgrade-test/colony-upgrade.js
  yarn.lock
Labels: maintenance, ready-for-review

#299 Updated contract loader to exact version 1.5.4
  greenkeeper.json
  package.json
  packages/colony-js-contract-loader-network/package.json
  packages/reputation-miner/package.json
  yarn.lock
Labels: maintenance

#244 Doc fixes collection
  docs/_Docs_DomainsSkills.md
  docs/_Docs_MetaColony.md
  docs/_Docs_NetworkOverview.md
  docs/_Docs_Pots.md
  docs/_Docs_Reputation.md
  docs/_Docs_Tasks.md
  docs/_Docs_Upgrades.md
Labels: documentation

#312 Upgrade truffle to next.9
  helpers/test-helper.js
  package.json
  test/colony-network-mining.js
  yarn.lock
Labels: maintenance

#313 chore(package): update ganache-cli to version 6.1.8
  .circleci/config.yml
  package.json
  yarn.lock
Labels: maintenance

#314 Split `startNextCycle` into two functions
  contracts/ColonyNetworkMining.sol
  contracts/IColonyNetwork.sol
  migrations/6_setup_meta_colony.js
  test/colony.js
  test/meta-colony.js
  test/reputation-update.js
Labels: maintenance

#307 Upgrade ethers to v4 Beta
  package.json
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/package.json
  packages/reputation-miner/patricia-test.js
  packages/reputation-miner/patricia.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongProofLogEntry.js
  test/colony-network-mining.js
  yarn.lock
Labels: maintenance

#309 Refactoring task update calls
  contracts/ColonyTask.sol
  contracts/IColony.sol
  gasCosts/gasCosts.js
  helpers/test-data-generator.js
  test/colony-funding.js
  test/colony-network-mining.js
  test/colony-task-work-rating.js
  test/colony.js
  test/meta-colony.js
  test/reputation-update.js
Labels: under-review

#311 Add ability to reputation miner to sync from scratch
  contracts/ColonyNetworkMining.sol
  contracts/IColonyNetwork.sol
  helpers/test-helper.js
  package.json
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/package.json
  test/colony-network-mining.js
  yarn.lock
Labels: ready-for-review

#320 Move ReputationMiningCycle to an EtherRouter pattern
  contracts/ColonyNetwork.sol
  contracts/ColonyNetworkMining.sol
  contracts/ColonyNetworkStorage.sol
  contracts/IColonyNetwork.sol
  contracts/IReputationMiningCycle.sol
  contracts/ReputationMiningCycle.sol
  contracts/ReputationMiningCycleRespond.sol
  contracts/ReputationMiningCycleStorage.sol
  gasCosts/gasCosts.js
  helpers/upgradable-contracts.js
  migrations/2_deploy_contracts.js
  migrations/6_setup_mining_cycle_resolver.js
  migrations/8_setup_meta_colony.js
  scripts/check-recovery.js
  scripts/check-storage.js
  test/colony-funding.js
  test/colony-network-mining.js
  test/colony.js
  test/meta-colony.js
  test/reputation-update.js
  test/token-locking.js
Labels: maintenance

#327 Switch parity to newer version download from working mirror
  .circleci/config.yml
  helpers/upgradable-contracts.js
  migrations/8_setup_meta_colony.js
  parity-genesis.template.json
  scripts/resetParity.sh
  scripts/start-blockchain-client.sh
Labels: maintenance
