Repository JoinColony/colonyNetwork, pull requests merged in 2018-10, with the labels that each got.

#372 Upgrade to truffle5 beta.1
  package.json
  yarn.lock
Labels: maintenance

#374 CLNY goes to MetaColony, not ColonyNetwork
  contracts/ColonyNetworkAuction.sol
  test/colony-network-auction.js
Labels: ready-for-review

#376 Reduce external calls in submitJustificationRootHash
  contracts/ReputationMiningCycle.sol
Labels: ready-for-review

#378 Fixed link to authority client documentation
  docs/_Docs_Pots.md
Labels: documentation

#381 Review task lifecycle functions and guards
  contracts/Colony.sol
  contracts/ColonyAuthority.sol
  contracts/ColonyFunding.sol
  contracts/ColonyStorage.sol
  contracts/ColonyTask.sol
  contracts/IColony.sol
  gasCosts/gasCosts.js
  helpers/test-helper.js
  test/colony-task-work-rating.js
  test/colony-task.js
  test/colony.js
  test/meta-colony.js
Labels: under-review

#386 Delegate Network property setting to the Meta Colony
  .eslintrc
  contracts/Colony.sol
  contracts/ColonyAuthority.sol
  contracts/ColonyFunding.sol
  contracts/ColonyNetwork.sol
  contracts/ColonyNetworkMining.sol
  contracts/ColonyNetworkStorage.sol
  contracts/ColonyStorage.sol
  contracts/IColony.sol
  contracts/IColonyNetwork.sol
  contracts/IMetaColony.sol
  gasCosts/gasCosts.js
  helpers/test-data-generator.js
  helpers/upgradable-contracts.js
  migrations/4_setup_colony_version_resolver.js
  migrations/8_setup_meta_colony.js
  scripts/check-recovery.js
  test/colony-funding.js
  test/colony-network-mining.js
  test/colony-network-recovery.js
  test/colony-network.js
  test/colony-recovery.js
  test/colony-task.js
  test/colony.js
  test/meta-colony.js
  test/reputation-update.js
  upgrade-test/colony-upgrade.js
Labels: under-review

#402 24hr Mining Cycle
  contracts/ReputationMiningCycle.sol
  contracts/ReputationMiningCycleRespond.sol
  gasCosts/gasCosts.js
  helpers/constants.js
  helpers/test-helper.js
  packages/reputation-miner/ReputationMiner.js
  test/colony-funding.js
  test/colony-network-mining.js
  test/colony-network-recovery.js
  test/token-locking.js
Labels: ready-for-review

#390 Bug Bounty rules SLA, and terms&conditions
  docs/README.md
  docs/_bug_rules.md
  docs/_bug_terms.md
Labels: documentation
