Repository JoinColony/colonyNetwork, pull requests merged in 2018-07, with the labels that each got.

#224 Roles and permissions
  contracts/Authority.sol
  contracts/Colony.sol
  contracts/ColonyFunding.sol
  contracts/ColonyNetwork.sol
  contracts/ColonyStorage.sol
  contracts/ColonyTask.sol
  contracts/IColony.sol
  contracts/IColonyNetwork.sol
  gasCosts/gasCosts.js
  helpers/test-data-generator.js
  helpers/test-helper.js
  test/colony-funding.js
  test/colony-network.js
  test/colony.js
  test/meta-colony.js
  upgrade-test/colony-upgrade.js
Labels: ready-for-review

#259 Create Solidity-equivalent PatriciaJs
  .circleci/config.yml
  contracts/PatriciaTree/Data.sol
  contracts/PatriciaTree/PatriciaTree.sol
  package.json
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/patricia-test.js
  packages/reputation-miner/patricia.js
  test/colony-network-mining.js
Labels: ready-for-review

#263 Add contract events for deliverable submission and rating revelation
  contracts/ColonyTask.sol
  contracts/IColony.sol
  test/colony-task-work-rating.js
  test/colony.js
Labels: under-review

#262 Add slow=1000 mocha config
  truffle.js
Labels: maintenance, ready-for-review

#267 Switch token props to the correct types as per ERC20
  contracts/ColonyStorage.sol
  contracts/Token.sol
  test/meta-colony.js
Labels: maintenance

#253 Token Locking
  contracts/ColonyFunding.sol
  contracts/ColonyNetwork.sol
  contracts/ColonyNetworkStorage.sol
  contracts/ColonyStorage.sol
  contracts/IColony.sol
  contracts/IColonyNetwork.sol
  contracts/ITokenLocking.sol
  contracts/TokenLocking.sol
  contracts/TokenLockingStorage.sol
  gasCosts/gasCosts.js
  helpers/upgradable-contracts.js
  migrations/6_setup_token_locking.js
  scripts/check-storage.js
  test/colony-funding.js
  test/meta-colony.js
  test/token-locking.js
Labels: ready-for-review

#256 Fix denominator constraint
  contracts/ColonyFunding.sol
  contracts/IColony.sol
  gasCosts/gasCosts.js
  helpers/test-helper.js
  test/colony-funding.js
Labels: ready-for-review

#265 Compile warnings
  .eslintrc
  .soliumrc.json
  contracts/Authority.sol
  contracts/Colony.sol
  contracts/ColonyFunding.sol
  contracts/ColonyNetwork.sol
  contracts/ColonyNetworkAuction.sol
  contracts/ColonyNetworkStaking.sol
  contracts/ColonyNetworkStorage.sol
  contracts/ColonyStorage.sol
  contracts/ColonyTask.sol
  contracts/IColony.sol
  contracts/IReputationMiningCycle.sol
  contracts/PatriciaTree/IPatriciaTree.sol
  contracts/PatriciaTree/PatriciaTreeProofs.sol
  contracts/ReputationMiningCycle.sol
  packages/reputation-miner/patricia.js
Labels: maintenance, under-review

#273 Specify return variable names for functions with public interfaces
  contracts/IColony.sol
  contracts/IColonyNetwork.sol
  contracts/IReputationMiningCycle.sol
  contracts/ITokenLocking.sol
  contracts/PatriciaTree/IPatriciaTree.sol
Labels: documentation, maintenance

#254 Only allow auctions to be started at most once a month per token
  contracts/ColonyNetworkAuction.sol
  contracts/ColonyNetworkStorage.sol
  test/colony-network-auction.js
Labels: ready-for-review

#275 Make GreenKeeper lockfile updates strictly execute first in CI
  .circleci/config.yml
Labels: maintenance, ready-for-review

#284 Add husky package and move pre commit hooks to that
  package.json
  yarn.lock
Labels: maintenance, ready-for-review

#277 Moved staking logic to token locking contract
  contracts/ColonyNetworkMining.sol
  contracts/IColony.sol
  contracts/IColonyNetwork.sol
  contracts/IReputationMiningCycle.sol
  contracts/ITokenLocking.sol
  contracts/ReputationMiningCycle.sol
  contracts/TokenLocking.sol
  gasCosts/gasCosts.js
  helpers/test-data-generator.js
  helpers/upgradable-contracts.js
  migrations/2_deploy_contracts.js
  migrations/3_setup_colony_network.js
  migrations/5_setup_token_locking.js
  migrations/6_setup_meta_colony.js
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongProofLogEntry.js
  test/colony-network-mining.js
  test/meta-colony.js
  test/reputation-update.js
  test/token-locking.js
Labels: under-review

#291 Use existing CLNY contract at start of mining test
  test/colony-network-mining.js
Labels: bug

#285 Fix parent skill fetching
  contracts/ColonyNetwork.sol
  contracts/IColonyNetwork.sol
  helpers/test-data-generator.js
  helpers/test-helper.js
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/test/MaliciousReputationMinerExtraRep.js
  test/colony-network-mining.js
  test/meta-colony.js
Labels: under-review
