Repository JoinColony/colonyNetwork, pull requests merged in 2018-12, with the labels that each got.

#444 Add task diagrams and update old ones
  docs/_Docs_Colony.md
  docs/_Docs_DomainsSkills.md
  docs/_Docs_NetworkOverview.md
  docs/_Docs_Tasks.md
  docs/_Docs_Upgrades.md
  docs/img/Colony_Header.png
  docs/img/EtherRouter.svg
  docs/img/colonyNetwork_color.svg
  docs/img/delegateProxyCallchain_1.png
  docs/img/domains_1.png
  docs/img/domains_r1.svg
  docs/img/storage_1.png
  docs/img/taskCreation_1.png
  docs/img/taskModification_r2.png
  docs/img/taskPayout_1.png
  docs/img/taskRatings_r2.png
Labels: documentation

#454 Upgrade Truffle to (almost) truffle-next-18
  package.json
  yarn.lock
Labels: maintenance

#457 Fix parity download path
  .circleci/config.yml
Labels: maintenance, ready-for-review

#461 Move back to mainline Truffle 5.0.0-next releases
  package.json
  truffle.js
  yarn.lock
Labels: maintenance

#453 Big Old Test Refactor 2
  contracts/Colony.sol
  helpers/constants.js
  helpers/test-data-generator.js
  helpers/test-helper.js
  test/colony-funding.js
  test/colony-network-auction.js
  test/colony-network-mining.js
  test/colony-network-recovery.js
  test/colony-network.js
  test/colony-recovery.js
  test/colony-task.js
  test/colony.js
  test/meta-colony.js
  test/reputation-update.js
  test/token-locking.js
Labels: under-review

#463 Fixed wrong install order in docs
  docs/README.md
Labels: maintenance

#469 Add MAX_PAYOUT limit to setTaskPayout
  contracts/ColonyFunding.sol
  contracts/ColonyTask.sol
  helpers/constants.js
  helpers/test-data-generator.js
  test/colony-task-work-rating.js
  test/colony-task.js
  test/reputation-update.js
Labels: under-review

#471 Fix incomplete test
  test/reputation-update.js
Labels: ready-for-review

#475 Add getPot function
  contracts/Colony.sol
  contracts/ColonyDataTypes.sol
  contracts/ColonyFunding.sol
  contracts/IColony.sol
  test/colony.js
Labels: feature

#477 Remove the ability to change token on Colony once initialised
  contracts/Colony.sol
  contracts/ColonyAuthority.sol
  contracts/ColonyDataTypes.sol
  contracts/ColonyNetwork.sol
  contracts/IColony.sol
  test/colony-recovery.js
  test/colony.js
Labels: ready-for-review

#478 Fix stop blockchain script killing browser
  scripts/stop-blockchain-client.sh
Labels: under-review
