Repository JoinColony/colonyNetwork, pull requests merged in 2018-06, with the labels that each got.

#221 Rename ganache accounts file
  .gitignore
  .solcover.js
  helpers/test-helper.js
  scripts/start-blockchain-client.sh
Labels: maintenance

#229 Minor miner changes because the world is imperfect
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/ReputationMinerClient.js
Labels: maintenance

#216 Add events for more granularity during task changes
  contracts/ColonyFunding.sol
  contracts/ColonyTask.sol
  contracts/IColony.sol
  test/colony.js
Labels: under-review

#203 Task change nonce becomes task specific
  contracts/ColonyStorage.sol
  contracts/ColonyTask.sol
  contracts/IColony.sol
  gasCosts/gasCosts.js
  helpers/test-data-generator.js
  helpers/test-helper.js
  test/colony.js
Labels: under-review

#235 Use actual bytes32 hex encoded ipfs hash in tests
  helpers/constants.js
  test/colony.js
  upgrade-test/colony-upgrade.js
Labels: maintenance, ready-for-review

#228 Implement three-point ratings
  contracts/ColonyStorage.sol
  contracts/ColonyTask.sol
  contracts/IColony.sol
  helpers/constants.js
  test/colony-funding.js
  test/colony-network-mining.js
  test/colony-task-work-rating.js
  test/reputation-update.js
Labels: under-review

#231 Add content for running the usable reputation mining client.
  docs/_Docs_GetStarted.md
Labels: ready-for-review

#233 NetworkLoader for Colony contracts
  .circleci/config.yml
  packages/colony-contract-loader-network/.gitignore
  packages/colony-contract-loader-network/Readme.md
  packages/colony-contract-loader-network/config.json
  packages/colony-contract-loader-network/contracts/static/EtherRouter.json
  packages/colony-contract-loader-network/contracts/static/Token.json
  packages/colony-contract-loader-network/contracts/versioned/rinkeby-v1/Authority.json
  packages/colony-contract-loader-network/contracts/versioned/rinkeby-v1/IColony.json
  packages/colony-contract-loader-network/contracts/versioned/rinkeby-v1/IColonyNetwork.json
  packages/colony-contract-loader-network/jest.conf.json
  packages/colony-contract-loader-network/package.json
  packages/colony-contract-loader-network/src/NetworkLoader.js
  packages/colony-contract-loader-network/src/__tests__/NetworkLoader.test.js
  packages/colony-contract-loader-network/src/index.js
  yarn.lock
Labels: feature, ready-for-review

#236 Update ganache-cli to 6.1.3
  .circleci/config.yml
  contracts/ColonyFunding.sol
  migrations/2_deploy_contracts.js
  package.json
  scripts/start-blockchain-client.sh
  test/colony-network-mining.js
  truffle.js
Labels: greenkeeper, in-progress

#238 Supply the selected network ID to the loader (`colony-network-contract-loader` package)
  .eslintignore
  packages/colony-js-contract-loader-network/package.json
  packages/colony-js-contract-loader-network/src/NetworkLoader.js
  packages/colony-js-contract-loader-network/src/__tests__/NetworkLoader.test.js
  yarn.lock
Labels: bug

#240 Improve payout accounting
  contracts/ColonyFunding.sol
  contracts/ColonyStorage.sol
  contracts/ColonyTask.sol
  contracts/IColony.sol
  test/colony-funding.js
  test/colony-task-work-rating.js
  test/colony.js
Labels: bug, under-review

#245 Restrict defunding pot below task budget
  contracts/ColonyFunding.sol
  test/colony-funding.js
Labels: bug, ready-for-review

#250 Add DomainAdded/PotAdded events
  contracts/Colony.sol
  contracts/ColonyStorage.sol
  contracts/ColonyTask.sol
  contracts/IColony.sol
  helpers/test-data-generator.js
  helpers/test-helper.js
  test/colony.js
Labels: feature, ready-for-review

#242 network-loader fixes
  packages/colony-js-contract-loader-network/contracts/static/Token.json
  packages/colony-js-contract-loader-network/package.json
Labels: ready-for-review
