Repository JoinColony/colonyNetwork, pull requests merged in 2019-06, with the labels that each got.

#630 Arbitration Role in IColony
  contracts/Colony.sol
  contracts/ColonyAuthority.sol
  contracts/ColonyNetwork.sol
  contracts/IColony.sol
  docs/_Interface_IColony.md
  test/contracts-network/colony-permissions.js
Labels: feature, ready-for-review

#632 Revert "Arbitration Role in IColony"
  contracts/Colony.sol
  contracts/ColonyAuthority.sol
  contracts/ColonyNetwork.sol
  contracts/IColony.sol
  docs/_Interface_IColony.md
  test/contracts-network/colony-permissions.js
Labels: maintenance, under-review

#634 Add trailing-whitespace rules to eslint and solium
  .eslintrc
  .soliumrc.json
  contracts/ColonyFunding.sol
  contracts/ColonyNetwork.sol
  contracts/ColonyNetworkAuction.sol
  contracts/ColonyNetworkDataTypes.sol
  contracts/ColonyNetworkStorage.sol
  contracts/EtherRouter.sol
  contracts/IColony.sol
  contracts/PatriciaTree/IPatriciaTree.sol
  contracts/ReputationMiningCycleDataTypes.sol
  contracts/ReputationMiningCycleRespond.sol
  contracts/extensions/OldRolesFactory.sol
  contracts/extensions/OneTxPaymentFactory.sol
  contracts/testHelpers/TaskSkillEditing.sol
  docs/_Interface_IColony.md
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/ReputationMinerClient.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongResponse.js
Labels: maintenance

#636 Bump Colony version to 2
  contracts/Colony.sol
  contracts/ColonyNetwork.sol
  contracts/IColonyNetwork.sol
  docs/_Interface_IColonyNetwork.md
  helpers/test-data-generator.js
  migrations/4_setup_colony_version_resolver.js
  test/contracts-network/colony-network.js
Labels: maintenance

#631 Update mining docs for Goerli, better errors and logging for miner
  docs/_Docs_ReputationMining.md
  packages/reputation-miner/ReputationMiner.js
Labels: maintenance

#625 Documentation Improvements
  docs/CONTRIBUTING.md
  docs/README.md
  docs/_Docs_Extensions.md
  docs/_Docs_GetStarted.md
  docs/_Docs_Overview.md
  docs/_Docs_Permissions.md
  docs/_Docs_Releases.md
  docs/_Docs_ReputationMining.md
  docs/_Docs_Upgrades.md
  docs/_Intro_Welcome.md
  docs/img/colonyNetwork_diagram_r10.png
  docs/img/colonyNetwork_diagram_r11.png
  docs/img/colonyNetwork_diagram_r12.jpg
Labels: documentation

#638 Greenkeeper/prettier 1.18.0
  package.json
  test/contracts-network/colony-network-auction.js
  yarn.lock
Labels: maintenance

#640 🙈 Errata in docs
  docs/_Docs_ReputationMining.md
  docs/_Intro_Welcome.md
  docs/img/colonyNetwork_diagram_r12.jpg
  docs/img/colonyNetwork_diagram_r12.png
Labels: documentation

#643 Improve code coverage
  contracts/testHelpers/FunctionsNotAvailableOnColony.sol
  helpers/test-helper.js
  package.json
  scripts/check-recovery.js
  test/contracts-network/colony-network-auction.js
  test/contracts-network/colony-network-recovery.js
  test/contracts-network/colony-network.js
  test/contracts-network/colony-recovery.js
  yarn.lock
Labels: maintenance

#649 Add network configurations and fork setup
  package.json
  truffle.js
Labels: maintenance

#650 Update reputation oracle documentation
  docs/_Docs_ReputationMining.md
Labels: documentation

#648 Revert Reverted Arbitration role (the correct way)
  contracts/Colony.sol
  contracts/ColonyAuthority.sol
  contracts/ColonyNetwork.sol
  contracts/IColony.sol
  contracts/extensions/OldRoles.sol
  docs/_Interface_IColony.md
  test/contracts-network/colony-permissions.js
Labels: feature, under-review

#654 Greenkeeper/solidity parser antlr 0.4.5
  package.json
  scripts/check-auth.js
  yarn.lock
Labels: maintenance

#658 Fix nightly build
  contracts/ColonyTask.sol
  contracts/TokenLocking.sol
Labels: maintenance

#660 chore(package): update eslint-plugin-flowtype to version 3.11.1
  package.json
  yarn.lock
Labels: maintenance
