Repository JoinColony/colonyNetwork, pull requests merged in 2019-01, with the labels that each got.

#484 Fix bug with deposit timestamp in claimRewardPayout
  contracts/ColonyFunding.sol
  test-gas-costs/gasCosts.js
  test/colony-funding.js
Labels: ready-for-review

#481 Clarify ownership of Network contracts
  .circleci/config.yml
  migrations/6_setup_mining_cycle_resolver.js
  package.json
  scripts/generate-test-contracts.sh
  test-gas-costs/gasCosts.js
  test-upgrade/colony-network-upgrade.js
  test-upgrade/colony-upgrade.js
  test-upgrade/reputation-mining-cycle-upgrade.js
Labels: under-review

#480 Optimise contract storage layout
  contracts/Colony.sol
  contracts/ColonyAuthority.sol
  contracts/ColonyDataTypes.sol
  contracts/ColonyFunding.sol
  contracts/ColonyNetworkStorage.sol
  contracts/ColonyStorage.sol
  contracts/ColonyTask.sol
  contracts/CommonStorage.sol
  contracts/IColony.sol
  contracts/ReputationMiningCycleStorage.sol
  test/colony-network-recovery.js
Labels: under-review

#482 (Maybe) fix flickery test
  helpers/test-helper.js
  test/colony-network-mining.js
Labels: under-review

#479 Integrate OpenZeppelin token
  .circleci/config.yml
  .solcover.js
  contracts/Colony.sol
  contracts/ERC20Extended.sol
  contracts/ERC20ExtendedToken.sol
  helpers/test-data-generator.js
  helpers/test-helper.js
  package.json
  scripts/check-recovery.js
  scripts/check-storage.js
  scripts/provision-token-contracts.sh
  test-gas-costs/gasCosts.js
  test-upgrade/colony-network-upgrade.js
  test-upgrade/colony-upgrade.js
  test/colony-funding.js
  test/colony-network-auction.js
  test/colony-network-recovery.js
  test/colony-network.js
  test/colony-task.js
  test/colony-token-integrations.js
  test/colony.js
  test/token-locking.js
  yarn.lock
Labels: under-review

#492 Maintenance package updates
  package.json
  packages/reputation-miner/package.json
  yarn.lock
Labels: maintenance, ready-for-review

#409 Child reputation updates edge cases and fixes
  contracts/Colony.sol
  contracts/IReputationMiningCycle.sol
  contracts/ReputationMiningCycle.sol
  contracts/ReputationMiningCycleDataTypes.sol
  contracts/ReputationMiningCycleRespond.sol
  contracts/ReputationMiningCycleStorage.sol
  helpers/constants.js
  helpers/test-helper.js
  packages/reputation-miner/.eslintrc
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/test/MaliciousReputationMinerClaimNoOriginReputation.js
  packages/reputation-miner/test/MaliciousReputationMinerClaimWrongChildReputation.js
  packages/reputation-miner/test/MaliciousReputationMinerClaimWrongOriginReputation.js
  packages/reputation-miner/test/MaliciousReputationMinerExtraRep.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongProofLogEntry.js
  test/colony-funding.js
  test/colony-network-mining.js
  test/reputation-update.js
Labels: under-review

#499 Fix broken links in docs
  docs/_Docs_DomainsSkills.md
  docs/_Docs_MetaColony.md
  docs/_Docs_NetworkOverview.md
  docs/_Docs_Pots.md
  docs/_Docs_Reputation.md
  docs/_Docs_ReputationMining.md
  docs/_Docs_Tasks.md
  docs/_bug_terms.md
Labels: documentation

#503 Upgrade ethlint to latest which resolves last set of warnings in our contracts
  .soliumrc.json
  package.json
  yarn.lock
Labels: ready-for-review

#504 Consistent contract references in storage
  contracts/Colony.sol
  contracts/ColonyFunding.sol
  contracts/ColonyStorage.sol
  contracts/ColonyTask.sol
Labels: ready-for-review

#507 Remove redundant global skill creation
  test/reputation-mining/happy-paths.js
Labels: ready-for-review

#505 Enable mythril nightly run
  .circleci/config.yml
  contracts/ColonyNetwork.sol
  package.json
  yarn.lock
Labels: maintenance

#508 Throw error for insufficient miner stake
  packages/reputation-miner/ReputationMiner.js
  test/reputation-mining/root-hash-submissions.js
Labels: under-review

#512 Enable mythril nightlies
  .circleci/config.yml
Labels: maintenance

#498 Changed data-type of element in struct of nUpdates & nPreviousUpdates from uint256 to uint128
  contracts/ColonyNetwork.sol
  contracts/ColonyNetworkDataTypes.sol
  contracts/ColonyNetworkMining.sol
  contracts/IColonyNetwork.sol
  contracts/IReputationMiningCycle.sol
  contracts/ReputationMiningCycle.sol
  contracts/ReputationMiningCycleDataTypes.sol
  contracts/ReputationMiningCycleRespond.sol
  test/colony-network-recovery.js
Labels: under-review

#510 Upgrade to babel 7 and resolve source map support failure in tests
  .babelrc
  .circleci/config.yml
  .nvmrc
  babel.config.js
  helpers/test-helper.js
  package.json
  packages/colony-js-contract-loader-network/.babelrc
  packages/colony-js-contract-loader-network/package.json
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/bin/index.js
  packages/reputation-miner/package.json
  packages/reputation-miner/test/MaliciousReputationMinerUnsure.js
  test-gas-costs/gasCosts.js
  truffle.js
  yarn.lock
Labels: maintenance

#506 Prevent reputation being changed during insertion of new one
  contracts/IReputationMiningCycle.sol
  contracts/ReputationMiningCycleRespond.sol
  helpers/test-helper.js
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/test/MaliciousReputationMinerAddNewReputation.js
  packages/reputation-miner/test/MaliciousReputationMinerClaimNew.js
  packages/reputation-miner/test/MaliciousReputationMinerClaimNoOriginReputation.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongProofLogEntry.js
  test/reputation-mining/dispute-resolution-misbehaviour.js
  test/reputation-mining/disputes-over-child-reputation.js
  test/reputation-mining/types-of-disagreement.js
Labels: under-review

#518 Fix issue around origin reputation
  contracts/IReputationMiningCycle.sol
  contracts/ReputationMiningCycleRespond.sol
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/test/MaliciousReputationMinerClaimNoOriginReputation.js
  packages/reputation-miner/test/MaliciousReputationMinerGlobalOriginNotChildOrigin.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongProofLogEntry.js
  test/reputation-mining/dispute-resolution-misbehaviour.js
  test/reputation-mining/disputes-over-child-reputation.js
Labels: bug, in-progress
