Repository JoinColony/colonyNetwork, pull requests merged in 2019-10, with the labels that each got.

#718 Do not use user-supplied branchmasks if possible
  .eslintrc
  contracts/IReputationMiningCycle.sol
  contracts/ReputationMiningCycle.sol
  docs/_Interface_IReputationMiningCycle.md
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongJRH.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongJRHRightNNodes.js
  test/reputation-system/dispute-resolution-misbehaviour.js
  test/reputation-system/happy-paths.js
  test/reputation-system/types-of-disagreement.js
Labels: maintenance, under-review

#710 Bump ganache-cli to 6.7.0
  package.json
  packages/reputation-miner/ReputationMiner.js
  yarn.lock
Labels: on-hold

#690 Fix nightly security build
  contracts/Colony.sol
  contracts/ColonyAuthority.sol
  contracts/ColonyNetworkStorage.sol
  contracts/ColonyStorage.sol
  contracts/CommonStorage.sol
  contracts/DomainRoles.sol
  contracts/ReputationMiningCycle.sol
  contracts/ReputationMiningCycleStorage.sol
  contracts/Resolver.sol
  contracts/TokenLockingStorage.sol
  contracts/ens/ENSRegistry.sol
  contracts/extensions/OneTxPayment.sol
  contracts/testHelpers/TransferTest.sol
  package.json
  scripts/process-truffle-security.js
  slither.db.json
  yarn.lock
Labels: bug, in-progress

#629 Polish off the mining client and make it more resillient
  .eslintrc
  helpers/test-helper.js
  packages/reputation-miner/Dockerfile
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/ReputationMinerClient.js
  packages/reputation-miner/adapters/console.js
  packages/reputation-miner/adapters/slack.js
  packages/reputation-miner/bin/index.js
  packages/reputation-miner/package.json
  packages/reputation-miner/test/MaliciousReputationMinerWrongJRHRightNNodes.js
  test/reputation-system/reputation-mining-client/client-auto-functionality.js
  yarn.lock
Labels: in-progress, maintenance
