Repository JoinColony/colonyNetwork, pull requests merged in 2019-11, with the labels that each got.

#693 Add support for Expenditures
  contracts/Colony.sol
  contracts/ColonyAuthority.sol
  contracts/ColonyDataTypes.sol
  contracts/ColonyExpenditure.sol
  contracts/ColonyFunding.sol
  contracts/ColonyStorage.sol
  contracts/CommonStorage.sol
  contracts/IColony.sol
  docs/_Interface_IColony.md
  helpers/test-data-generator.js
  helpers/upgradable-contracts.js
  migrations/4_setup_colony_version_resolver.js
  scripts/docgen.js
  test-upgrade/colony-upgrade.js
  test/contracts-network/colony-expenditure.js
  test/contracts-network/colony-permissions.js
Labels: feature, ready-for-review

#731 Remove 'newest reputation' proofs from mining disputes
  contracts/IReputationMiningCycle.sol
  contracts/ReputationMiningCycle.sol
  contracts/ReputationMiningCycleDataTypes.sol
  contracts/ReputationMiningCycleRespond.sol
  docs/_Interface_IReputationMiningCycle.md
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/test/MaliciousReputationMinerUnsure.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongNewestReputation.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongProofLogEntry.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongResponse.js
  test/reputation-system/dispute-resolution-misbehaviour.js
  test/reputation-system/disputes-over-child-reputation.js
  test/reputation-system/types-of-disagreement.js
Labels: maintenance, under-review

#738 Greenkeeper/prettier 1.19.1
  .eslintrc
  package.json
  scripts/check-auth.js
  scripts/check-recovery.js
  test/reputation-system/dispute-resolution-misbehaviour.js
  yarn.lock
Labels: ready-for-review
