Repository JoinColony/colonyNetwork, pull requests merged in 2019-03, with the labels that each got.

#561 Give Colony founder recovery role by default
  contracts/ColonyNetwork.sol
  test/colony-recovery.js
Labels: feature

#570 Fix token authority instantiation in migrations
  .gitmodules
  helpers/test-data-generator.js
  migrations/8_setup_meta_colony.js
Labels: maintenance

#568 Remove redundant auth from ReputationMiningCycleStorage
  contracts/ReputationMiningCycleStorage.sol
Labels: maintenance

#572 Downgrade eth-gas-reporter
  package.json
  yarn.lock
Labels: maintenance

#576 Do not penalise worker's skill awarded
  contracts/ColonyTask.sol
  test/reputation-update.js
Labels: under-review
