Repository JoinColony/colonyNetwork, pull requests merged in 2019-07, with the labels that each got.

#659 Subdomain single tx payment funds can be from root
  contracts/extensions/OneTxPayment.sol
  test/extensions/one-tx-payment.js
Labels: feature, under-review

#667 Allow users and colonies to update their OrbitDB store address
  .circleci/config.yml
  contracts/Colony.sol
  contracts/ColonyAuthority.sol
  contracts/ColonyNetworkENS.sol
  contracts/IColony.sol
  contracts/IColonyNetwork.sol
  docs/_Interface_IColony.md
  docs/_Interface_IColonyNetwork.md
  package.json
  test-upgrade/2to3/2to3.js
  test/contracts-network/colony-network.js
  test/contracts-network/colony-recovery.js
Labels: feature

#666 Enable slither analyzer in nightly build
  .circleci/config.yml
  contracts/Colony.sol
  contracts/ColonyFunding.sol
  contracts/ColonyNetwork.sol
  contracts/ColonyNetworkAuction.sol
  contracts/ColonyNetworkMining.sol
  package.json
  slither.config.json
  slither.db.json
  test/contracts-network/colony-network-auction.js
  test/contracts-network/colony.js
Labels: maintenance

#671 Fix URI for reputation tree visualizer data
  packages/reputation-miner/viz/repTree.html
Labels: ready-for-review

#674 Update babel
  package.json
  packages/reputation-miner/package.json
  yarn.lock
Labels: maintenance

#678 Add Arbitration role setup in colony upgrade
  contracts/Colony.sol
  contracts/ColonyAuthority.sol
  test-upgrade/2to3/2to3.js
Labels: bug

#679 Upgrade web3-utils to 1.0.0
  package.json
  packages/reputation-miner/package.json
  yarn.lock
Labels: greenkeeper

#676 Update eth-gas-reporter usage
  .circleci/config.yml
  codechecks.yml
  package.json
  yarn.lock
Labels: under-review

#680 Debug codechecks
  .circleci/config.yml
Labels: bug, ready-for-review

#681 Fix nightly build
  .circleci/config.yml
  package.json
  slither.db.json
Labels: ready-for-review

#686 Add ability to get all domain roles of a user
  contracts/Colony.sol
  contracts/IColony.sol
  docs/_Interface_IColony.md
  test/contracts-network/colony-permissions.js
  yarn.lock
Labels: under-review
