Repository JoinColony/colonyNetwork, pull requests merged in 2019-12, with the labels that each got.

#742 Update slither ignores
  slither.db.json
Labels: maintenance, ready-for-review

#746 Greenkeeper/eslint plugin flowtype 4.5.2
  package.json
  yarn.lock
Labels: ready-for-review

#747 Greenkeeper/husky 3.1.0
  package.json
  yarn.lock
Labels: ready-for-review

#749 Greenkeeper/eth gas reporter 0.2.14
  package.json
  yarn.lock
Labels: ready-for-review

#750 Fix the nightly
  package.json
  slither.db.json
  yarn.lock
Labels: under-review

#752 chore(package): update eslint-plugin-import to version 2.19.1
  package.json
Labels: ready-for-review

#755 Change default rating from 3 to 2
  contracts/ColonyTask.sol
  test/contracts-network/colony-task-work-rating.js
  test/contracts-network/reputation-update.js
Labels: ready-for-review

#758 Greenkeeper/truffle 5.1.4
  package.json
  yarn.lock
Labels: ready-for-review
