Repository JoinColony/colonyNetwork, pull requests merged in 2019-05, with the labels that each got.

#599 Fix reputation mining issues
  contracts/IReputationMiningCycle.sol
  contracts/ReputationMiningCycle.sol
  contracts/ReputationMiningCycleRespond.sol
  contracts/ReputationMiningCycleStorage.sol
  helpers/test-helper.js
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongProofLogEntry.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongResponse.js
  test/reputation-mining/basic-functionality.js
  test/reputation-mining/dispute-resolution-misbehaviour.js
  test/reputation-mining/disputes-over-child-reputation.js
  test/reputation-mining/happy-paths.js
  test/reputation-mining/root-hash-submissions.js
  test/reputation-mining/types-of-disagreement.js
Labels: maintenance

#600 Fixed some grammar and added links
  docs/_Docs_Overview.md
  docs/_Intro_Welcome.md
Labels: documentation

#604 Add Goerli to supported Infura networks
  packages/reputation-miner/bin/index.js
Labels: maintenance, ready-for-review

#603 Docs/glider
  docs/README.md
  docs/_Docs_Extensions.md
  docs/_Docs_GetStarted.md
  docs/_Docs_Overview.md
  docs/_Docs_Permissions.md
  docs/_Docs_Releases.md
  docs/_Intro_Welcome.md
  docs/_TLDR_Colony.md
  docs/_TLDR_Reputation.md
  docs/_TLDR_Tasks.md
  docs/_bug_rules.md
  docs/img/colonyNetwork_diagram_r11.png
  docs/img/glider_fullColor.svg
Labels: documentation, ready-for-review

#612 Fix broken link to whitepaper
  docs/_Intro_Welcome.md
Labels: documentation

#611 Add Goerli to truffle config
  package.json
  packages/reputation-miner/package.json
  truffle.js
  yarn.lock
Labels: maintenance

#615 Update role change events to include domainId
  contracts/Colony.sol
  contracts/ColonyDataTypes.sol
  contracts/ContractRecovery.sol
Labels: maintenance, under-review

#616 Upgrade to latest solc 0.5.8
  .circleci/config.yml
  helpers/test-data-generator.js
  package.json
  test-gas-costs/gasCosts.js
  test-upgrade/colony-network-upgrade.js
  test-upgrade/colony-upgrade.js
  test/colony-funding.js
  test/colony-network-auction.js
  test/colony-network.js
  test/colony-payment.js
  test/colony-reward-payouts.js
  test/colony-task.js
  test/colony.js
  test/reputation-update.js
  test/token-locking.js
  truffle.js
Labels: maintenance

#613 Add code coverage for Reputation mining client
  .circleci/config.yml
  .gitignore
  .nycrc
  babel.config.js
  package.json
  packages/reputation-miner/package.json
  test/contracts-network/colony-funding.js
  test/contracts-network/colony-network-auction.js
  test/contracts-network/colony-network-recovery.js
  test/contracts-network/colony-network.js
  test/contracts-network/colony-payment.js
  test/contracts-network/colony-permissions.js
  test/contracts-network/colony-recovery.js
  test/contracts-network/colony-reward-payouts.js
  test/contracts-network/colony-task-work-rating.js
  test/contracts-network/colony-task.js
  test/contracts-network/colony-token-integrations.js
  test/contracts-network/colony.js
  test/contracts-network/meta-colony.js
  test/contracts-network/reputation-basic-functionality.js
  test/contracts-network/reputation-update.js
  test/contracts-network/router-resolver.js
  test/contracts-network/token-locking.js
  test/reputation-system/client-calculations.js
  test/reputation-system/client-core-functionality.js
  test/reputation-system/client-sync-functionality.js
  test/reputation-system/dispute-resolution-misbehaviour.js
  test/reputation-system/disputes-over-child-reputation.js
  test/reputation-system/happy-paths.js
  test/reputation-system/root-hash-submissions.js
  test/reputation-system/types-of-disagreement.js
  yarn.lock
Labels: maintenance, ready-for-review

#617 Extract task signing helper functions
  helpers/task-review-signing.js
  helpers/test-data-generator.js
  helpers/test-helper.js
  package.json
  test-gas-costs/gasCosts.js
  test/contracts-network/colony-funding.js
  test/contracts-network/colony-permissions.js
  test/contracts-network/colony-task.js
  test/contracts-network/meta-colony.js
  yarn.lock
Labels: maintenance

#614 Docs updates for `glider-rc.1` -- "Get Started" with remix and truffle
  contracts/IColonyNetwork.sol
  docs/_Docs_GetStarted.md
  docs/_Docs_Releases.md
  docs/_Docs_ReputationMining.md
  docs/_TLDR_ReputationMining.md
  docs/_bug_rules.md
  package.json
Labels: documentation

#621 RepCycle Visualizer Improvements
  packages/reputation-miner/viz/repCycle.html
Labels: maintenance

#596 Real world mining client
  contracts/IReputationMiningCycle.sol
  contracts/ReputationMiningCycle.sol
  contracts/ReputationMiningCycleDataTypes.sol
  contracts/ReputationMiningCycleRespond.sol
  helpers/test-helper.js
  package.json
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/ReputationMinerClient.js
  packages/reputation-miner/bin/index.js
  packages/reputation-miner/test/ReputationMinerTestWrapper.js
  test/reputation-system/reputation-mining-client/client-auto-functionality.js
Labels: under-review

#622 Generate documentation for interface contracts
  contracts/IColony.sol
  contracts/IColonyNetwork.sol
  contracts/IEtherRouter.sol
  contracts/IMetaColony.sol
  contracts/IRecovery.sol
  contracts/IReputationMiningCycle.sol
  contracts/ITokenLocking.sol
  docs/_Interface_IColony.md
  docs/_Interface_IColonyNetwork.md
  docs/_Interface_IEtherRouter.md
  docs/_Interface_IMetaColony.md
  docs/_Interface_IRecovery.md
  docs/_Interface_IReputationMiningCycle.md
  docs/_Interface_ITokenLocking.md
  docs/doc.config.json
  docs/templates/_Interface_IColony.md
  docs/templates/_Interface_IColonyNetwork.md
  docs/templates/_Interface_IEtherRouter.md
  docs/templates/_Interface_IMetaColony.md
  docs/templates/_Interface_IRecovery.md
  docs/templates/_Interface_IReputationMiningCycle.md
  docs/templates/_Interface_ITokenLocking.md
  package.json
  scripts/docgen.js
  scripts/docgen/_API_Colony.template.md
  scripts/docgen/_API_ColonyNetwork.template.md
  scripts/docgen/_API_MetaColony.template.md
  scripts/docgen/_API_ReputationMiningCycle.template.md
  scripts/docgen/docgen.js
Labels: documentation
