Repository JoinColony/colonyNetwork, pull requests merged in 2019-02, with the labels that each got.

#525 Upgrade reputation-mining tests to bn-chai
  test/reputation-mining/basic-functionality.js
  test/reputation-mining/client-core-functionality.js
  test/reputation-mining/client-sync-functionality.js
  test/reputation-mining/dispute-resolution-misbehaviour.js
  test/reputation-mining/disputes-over-child-reputation.js
  test/reputation-mining/happy-paths.js
  test/reputation-mining/root-hash-submissions.js
  test/reputation-mining/types-of-disagreement.js
Labels: under-review

#528 Update links to colonyJS documentation
  docs/_Docs_DomainsSkills.md
  docs/_Docs_GetStarted.md
  docs/_Docs_NetworkOverview.md
  docs/_Docs_Pots.md
  docs/_Docs_Reputation.md
  docs/_Docs_Tasks.md
  packages/colony-js-contract-loader-network/Readme.md
Labels: documentation, ready-for-review

#526 Take bootstrapped tokens from claimed funds only
  contracts/Colony.sol
  test-gas-costs/gasCosts.js
  test/colony-network-recovery.js
  test/colony-reward-payouts.js
  test/colony.js
  test/token-locking.js
Labels: ready-for-review

#531 Rename Pot to FundingPot
  contracts/Colony.sol
  contracts/ColonyDataTypes.sol
  contracts/ColonyFunding.sol
  contracts/ColonyStorage.sol
  contracts/ColonyTask.sol
  contracts/IColony.sol
  helpers/test-data-generator.js
  test/colony-funding.js
  test/colony-network.js
  test/colony-task.js
  test/colony.js
  test/meta-colony.js
Labels: maintenance, ready-for-review

#530 Allow anyone to claim payout on Task Role's behalf
  contracts/ColonyFunding.sol
  test/colony-funding.js
  test/colony-reward-payouts.js
  test/colony-task.js
Labels: under-review

#535 Move to mythril release
  .circleci/config.yml
Labels: maintenance, ready-for-review

#532 Improvements of the FundingPot model
  contracts/Colony.sol
  contracts/ColonyDataTypes.sol
  contracts/ColonyFunding.sol
  contracts/ColonyTask.sol
  contracts/IColony.sol
  migrations/2_deploy_contracts.js
  test-gas-costs/gasCosts.js
  test/colony-funding.js
  test/colony-reward-payouts.js
  test/colony-task.js
  test/colony-token-integrations.js
  test/colony.js
  test/meta-colony.js
Labels: maintenance, ready-for-review

#540 Reputation mining client fixes and improvements
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/ReputationMinerClient.js
  packages/reputation-miner/bin/index.js
  packages/reputation-miner/package.json
Labels: bug

#541 Restore dbPath option in the client
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/ReputationMinerClient.js
  packages/reputation-miner/bin/index.js
Labels: maintenance

#538 Consolidate root hash submission checks
  helpers/test-helper.js
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongNNodes.js
  test/colony-network-recovery.js
  test/reputation-mining/dispute-resolution-misbehaviour.js
  test/reputation-mining/disputes-over-child-reputation.js
  test/reputation-mining/happy-paths.js
  test/reputation-mining/root-hash-submissions.js
  test/reputation-mining/types-of-disagreement.js
Labels: maintenance

#545 Upgrade breaking packages
  helpers/test-data-generator.js
  helpers/test-helper.js
  helpers/upgradable-contracts.js
  package-lock.json
  package.json
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/package.json
  packages/reputation-miner/patricia-base.js
  packages/reputation-miner/patricia-test.js
  test/reputation-update.js
  yarn.lock
Labels: maintenance

#552 Remove extra increments of challengeStepCompleted in respondToChallenge
  contracts/IReputationMiningCycle.sol
  contracts/ReputationMiningCycleRespond.sol
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/test/MaliciousReputationMinerClaimNoOriginReputation.js
  packages/reputation-miner/test/MaliciousReputationMinerClaimNoUserChildReputation.js
  packages/reputation-miner/test/MaliciousReputationMinerClaimWrongChildReputation.js
  packages/reputation-miner/test/MaliciousReputationMinerClaimWrongOriginReputation.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongNewestReputation.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongProofLogEntry.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongResponse.js
  test/reputation-mining/dispute-resolution-misbehaviour.js
  test/reputation-mining/disputes-over-child-reputation.js
Labels: maintenance
