Repository JoinColony/colonyNetwork, pull requests merged in 2019-04, with the labels that each got.

#580 Add logomark and update docs description
  docs/doc.config.json
  docs/img/logomark_colonyNetwork_blue.svg
  docs/img/logomark_colonyNetwork_dark.svg
Labels: documentation, under-review

#577 Docs/spring improvements
  docs/_Docs_GetStarted.md
  docs/_Docs_NetworkOverview.md
  docs/_Docs_Overview.md
  docs/_Docs_Releases.md
  docs/_Docs_Upgrades.md
  docs/_Intro_Welcome.md
  docs/_TLDR_Colony.md
  docs/_TLDR_Disputes.md
  docs/_TLDR_DomainsSkills.md
  docs/_TLDR_Glossary.md
  docs/_TLDR_MetaColony.md
  docs/_TLDR_Pots.md
  docs/_TLDR_Reputation.md
  docs/_TLDR_ReputationMining.md
  docs/_TLDR_Tasks.md
  docs/doc.config.json
  docs/img/architecture_colonyNetwork_r7.png
  scripts/docgen/_API_Colony.template.md
  scripts/docgen/_API_ColonyNetwork.template.md
  scripts/docgen/_API_MetaColony.template.md
  scripts/docgen/_API_ReputationMiningCycle.template.md
  scripts/docgen/docgen.js
  test/colony-reward-payouts.js
Labels: documentation, under-review

#553 Domain-level permissions
  .circleci/config.yml
  contracts/Colony.sol
  contracts/ColonyAuthority.sol
  contracts/ColonyDataTypes.sol
  contracts/ColonyFunding.sol
  contracts/ColonyNetwork.sol
  contracts/ColonyNetworkENS.sol
  contracts/ColonyPayment.sol
  contracts/ColonyStorage.sol
  contracts/ColonyTask.sol
  contracts/CommonAuthority.sol
  contracts/CommonStorage.sol
  contracts/ContractRecovery.sol
  contracts/DomainRoles.sol
  contracts/IColony.sol
  contracts/IRecovery.sol
  contracts/extensions/OldRoles.sol
  contracts/extensions/OneTxPayment.sol
  helpers/constants.js
  helpers/test-data-generator.js
  package.json
  scripts/check-auth.js
  scripts/check-recovery.js
  scripts/check-storage.js
  test-gas-costs/gasCosts.js
  test-upgrade/colony-upgrade.js
  test/colony-funding.js
  test/colony-network-recovery.js
  test/colony-network.js
  test/colony-payment.js
  test/colony-permissions.js
  test/colony-recovery.js
  test/colony-reward-payouts.js
  test/colony-task.js
  test/colony.js
  test/extensions/old-roles.js
  test/extensions/one-tx-payment.js
  test/meta-colony.js
  test/reputation-update.js
  test/token-locking.js
  yarn.lock
Labels: under-review

#579 Fix nightly security analysis job
  .circleci/config.yml
  package.json
  truffle.js
  yarn.lock
Labels: maintenance

#584 Assorted cleanups and improvements
  contracts/ColonyTask.sol
  contracts/IColony.sol
  contracts/IReputationMiningCycle.sol
  contracts/ReputationMiningCycle.sol
  contracts/TokenLocking.sol
  helpers/constants.js
  helpers/test-data-generator.js
  helpers/test-helper.js
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/patricia-base.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongProofLogEntry.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongResponse.js
  test/colony-funding.js
  test/colony-network-auction.js
  test/colony-network-recovery.js
  test/colony-network.js
  test/colony-payment.js
  test/colony-recovery.js
  test/colony-reward-payouts.js
  test/colony-task-work-rating.js
  test/colony-task.js
  test/colony.js
  test/extensions/one-tx-payment.js
  test/reputation-mining/basic-functionality.js
  test/reputation-mining/client-calculations.js
  test/reputation-mining/dispute-resolution-misbehaviour.js
  test/reputation-mining/disputes-over-child-reputation.js
  test/reputation-mining/happy-paths.js
  test/reputation-mining/root-hash-submissions.js
  test/reputation-mining/types-of-disagreement.js
  test/router-resolver.js
  test/token-locking.js
Labels: maintenance

#586 Split dispute resolution properties away from the Submission struct
  contracts/IReputationMiningCycle.sol
  contracts/ReputationMiningCycle.sol
  contracts/ReputationMiningCycleDataTypes.sol
  contracts/ReputationMiningCycleRespond.sol
  contracts/ReputationMiningCycleStorage.sol
  helpers/test-helper.js
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongProofLogEntry.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongResponse.js
  test/reputation-mining/dispute-resolution-misbehaviour.js
  test/reputation-mining/disputes-over-child-reputation.js
  test/reputation-mining/happy-paths.js
  test/reputation-mining/root-hash-submissions.js
  test/reputation-mining/types-of-disagreement.js
Labels: maintenance

#587 Fix e2e tests after merging DLP
  helpers/test-data-generator.js
  packages/reputation-miner/ReputationMiner.js
  test-system/end-to-end.js
Labels: maintenance

#591 Add factories for extension contracts
  contracts/extensions/ExtensionFactory.sol
  contracts/extensions/OldRolesFactory.sol
  contracts/extensions/OneTxPaymentFactory.sol
  migrations/2_deploy_contracts.js
  scripts/check-recovery.js
  scripts/check-storage.js
  test/extensions/old-roles.js
  test/extensions/one-tx-payment.js
Labels: feature
