Repository JoinColony/colonyNetwork, pull requests merged in 2020-02, with the labels that each got.

#779 Bump version from 3 to 4
  .circleci/config.yml
  contracts/Colony.sol
  contracts/IColony.sol
  docs/_Interface_IColony.md
  helpers/constants.js
  helpers/test-helper.js
  package.json
  packages/reputation-miner/ReputationMinerClient.js
  test-upgrade/2to3/2to3.js
  test/contracts-network/colony-network.js
  yarn.lock
Labels: maintenance, ready-for-review

#790 Update documentation for claimRewardPayout
  contracts/ColonyFunding.sol
  contracts/IColony.sol
  docs/_Interface_IColony.md
Labels: documentation, ready-for-review

#784 Allow creation of colonies with earlier version
  contracts/ColonyNetwork.sol
  contracts/IColonyNetwork.sol
  docs/_Interface_IColonyNetwork.md
  test/contracts-network/colony-network.js
Labels: under-review

#773 Remove reward time restrictions
  contracts/ColonyDataTypes.sol
  contracts/ColonyFunding.sol
  contracts/ColonyStorage.sol
  helpers/test-helper.js
  test-gas-costs/gasCosts.js
  test/contracts-network/colony-reward-payouts.js
  test/contracts-network/token-locking.js
Labels: under-review

#802 Bring all dev dependencies up to date
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/ReputationMinerClient.js
  test/contracts-network/colony-task.js
  test/reputation-system/dispute-resolution-misbehaviour.js
  yarn.lock
Labels: under-review

#741 Deprecate that pesky ArchitectureSubdomain role
  contracts/Colony.sol
  contracts/ColonyAuthority.sol
  contracts/ColonyDataTypes.sol
  contracts/ColonyStorage.sol
  helpers/constants.js
  test/contracts-network/colony-permissions.js
Labels: ready-for-review

#810 Prevent inappropriate byes being awarded to submissions during dispute
  .circleci/config.yml
  .solcover.js
  contracts/ReputationMiningCycle.sol
  contracts/ReputationMiningCycleStorage.sol
  helpers/test-helper.js
  parity-genesis.template.json
  scripts/resetParity.sh
  scripts/start-blockchain-client.sh
  test/reputation-system/dispute-resolution-misbehaviour.js
  test/reputation-system/root-hash-submissions.js
Labels: bug, under-review
