Repository JoinColony/colonyNetwork, pull requests merged in 2020-07, with the labels that each got.

#860 Add option to disable docker if desired
  truffle.js
Labels: maintenance

#863 Never restart if miner out of gas
  packages/reputation-miner/ReputationMinerClient.js
Labels: ready-for-review

#835 Coin Machine
  contracts/colony/Colony.sol
  contracts/colony/ColonyAuthority.sol
  contracts/colony/IColony.sol
  contracts/extensions/CoinMachine.sol
  contracts/extensions/CoinMachineFactory.sol
  docs/_Interface_IColony.md
  docs/_Interface_IColonyNetwork.md
  docs/_Interface_ITokenLocking.md
  helpers/test-data-generator.js
  helpers/test-helper.js
  scripts/check-recovery.js
  scripts/check-storage.js
  test/extensions/coin-machine.js
Labels: feature, ready-for-review

#862 Add CLNY issuance control / automation mechanisms
  contracts/colony/Colony.sol
  contracts/colony/ColonyAuthority.sol
  contracts/colony/IMetaColony.sol
  contracts/colonyNetwork/ColonyNetwork.sol
  contracts/colonyNetwork/ColonyNetworkMining.sol
  contracts/colonyNetwork/ColonyNetworkStorage.sol
  contracts/colonyNetwork/IColonyNetwork.sol
  contracts/reputationMiningCycle/ReputationMiningCycle.sol
  contracts/tokenLocking/ITokenLocking.sol
  helpers/test-helper.js
  test/contracts-network/meta-colony.js
  test/reputation-system/root-hash-submissions.js
Labels: ready-for-review
