Repository JoinColony/colonyNetwork, pull requests merged in 2020-04, with the labels that each got.

#830 Fix blockchain start script error on process termination
  scripts/stop-blockchain-client.sh
Labels: maintenance

#833 Reset finishUpgrade for v4
  contracts/colony/Colony.sol
Labels: maintenance, ready-for-review

#834 Fix accounting of nonRewardPotsTotal
  contracts/colony/ColonyFunding.sol
  docs/_Interface_IColonyNetwork.md
  test/contracts-network/colony-reward-payouts.js
Labels: ready-for-review
