Repository JoinColony/colonyNetwork, pull requests merged in 2020-12, with the labels that each got.

#897 Add maxTotal to cap total tokens available
  contracts/extensions/CoinMachine.sol
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony.js
  test/extensions/coin-machine.js
Labels: under-review

#906 Make sure SoliditySHA3 knows shortIDs are strings
  helpers/constants.js
  test/extensions/voting-rep.js
Labels: maintenance, ready-for-review

#904 Add payoutWhitelist to ColonyNetwork
  contracts/colony/Colony.sol
  contracts/colony/ColonyAuthority.sol
  contracts/colony/ColonyFunding.sol
  contracts/colony/IMetaColony.sol
  contracts/colonyNetwork/ColonyNetwork.sol
  contracts/colonyNetwork/ColonyNetworkDataTypes.sol
  contracts/colonyNetwork/ColonyNetworkStorage.sol
  contracts/colonyNetwork/IColonyNetwork.sol
  docs/_Interface_IColonyNetwork.md
  docs/_Interface_IMetaColony.md
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony-funding.js
  test/contracts-network/meta-colony.js
Labels: ready-for-review

#905 Add further events and functions required by app
  contracts/colony/Colony.sol
  contracts/colony/ColonyAuthority.sol
  contracts/colony/ColonyDataTypes.sol
  contracts/colony/IColony.sol
  contracts/colonyNetwork/ColonyNetwork.sol
  contracts/colonyNetwork/ColonyNetworkDataTypes.sol
  contracts/colonyNetwork/IColonyNetwork.sol
  contracts/extensions/OneTxPayment.sol
  contracts/extensions/TokenSupplier.sol
  docs/_Interface_IColony.md
  docs/_Interface_IColonyNetwork.md
  helpers/constants.js
  helpers/test-data-generator.js
  helpers/test-helper.js
  test-gas-costs/gasCosts.js
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony-network.js
  test/contracts-network/colony-reward-payouts.js
  test/contracts-network/colony-token-integrations.js
  test/contracts-network/colony.js
  test/contracts-network/router-resolver.js
  test/extensions/one-tx-payment.js
Labels: ready-for-review

#909 Test extensions function as intended when installed in subdomains only
  contracts/extensions/FundingQueue.sol
  test/extensions/coin-machine.js
  test/extensions/funding-queue.js
  test/extensions/one-tx-payment.js
  test/extensions/voting-rep.js
Labels: ready-for-review

#882 Add support for Annotations
  contracts/colony/Colony.sol
  contracts/colony/ColonyDataTypes.sol
  contracts/colony/IColony.sol
  contracts/extensions/VotingReputation.sol
  docs/_Interface_IColony.md
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony.js
Labels: feature, ready-for-review

#913 OneTxPayment event changes
  .gitignore
  contracts/colony/ColonyDataTypes.sol
  contracts/colony/ColonyFunding.sol
  contracts/colony/ColonyPayment.sol
  contracts/extensions/ColonyExtension.sol
  contracts/extensions/OneTxPayment.sol
  migrations/3_setup_colony_network.js
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony-payment.js
  test/extensions/one-tx-payment.js
Labels: ready-for-review

#914 Prevent burning of tokens by colony without appropriate bookkeeping
  contracts/colony/Colony.sol
  contracts/colony/ColonyAuthority.sol
  contracts/colony/ColonyDataTypes.sol
  contracts/colony/IColony.sol
  docs/_Interface_IColony.md
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony.js
Labels: ready-for-review
