Repository JoinColony/colonyNetwork, pull requests merged in 2020-08, with the labels that each got.

#760 Arbitration State Changes
  contracts/colony/Colony.sol
  contracts/colony/ColonyAuthority.sol
  contracts/colony/ColonyExpenditure.sol
  contracts/colony/IColony.sol
  docs/_Interface_IColony.md
  docs/_Interface_IColonyNetwork.md
  docs/_Interface_IMetaColony.md
  docs/_Interface_ITokenLocking.md
  test/contracts-network/colony-expenditure.js
Labels: ready-for-review

#842 Stagger allowed miner responses during a dispute
  contracts/colony/IColony.sol
  contracts/reputationMiningCycle/IReputationMiningCycle.sol
  contracts/reputationMiningCycle/ReputationMiningCycle.sol
  contracts/reputationMiningCycle/ReputationMiningCycleBinarySearch.sol
  contracts/reputationMiningCycle/ReputationMiningCycleCommon.sol
  contracts/reputationMiningCycle/ReputationMiningCycleDataTypes.sol
  contracts/reputationMiningCycle/ReputationMiningCycleRespond.sol
  contracts/tokenLocking/ITokenLocking.sol
  docs/_Interface_IColony.md
  docs/_Interface_IColonyNetwork.md
  docs/_Interface_IReputationMiningCycle.md
  docs/_Interface_ITokenLocking.md
  helpers/constants.js
  helpers/test-helper.js
  helpers/upgradable-contracts.js
  migrations/2_deploy_contracts.js
  migrations/6_setup_mining_cycle_resolver.js
  packages/reputation-miner/ReputationMinerClient.js
  scripts/check-recovery.js
  scripts/solium.sh
  test-gas-costs/gasCosts.js
  test-upgrade/reputation-mining-cycle-upgrade.js
  test/contracts-network/colony-network-recovery.js
  test/contracts-network/reputation-basic-functionality.js
  test/extensions/coin-machine.js
  test/extensions/funding-queue.js
  test/reputation-system/dispute-resolution-misbehaviour.js
  test/reputation-system/disputes-over-child-reputation.js
  test/reputation-system/happy-paths.js
  test/reputation-system/reputation-mining-client/client-auto-functionality.js
  test/reputation-system/root-hash-submissions.js
  test/reputation-system/types-of-disagreement.js
Labels: ready-for-review

#869 Change glob choosing tests to run under coverage
  docs/_Interface_IColonyNetwork.md
  docs/_Interface_IReputationMiningCycle.md
  package.json
Labels: maintenance, ready-for-review

#864 Update ganache-cli
  package.json
  yarn.lock
Labels: maintenance, under-review
