Repository JoinColony/colonyNetwork, pull requests merged in 2020-09, with the labels that each got.

#866 Add storage layout smoke tests
  .circleci/config.yml
  contracts/common/CommonStorage.sol
  contracts/common/ContractRecovery.sol
  package.json
  test-smoke/colony-storage-consistent.js
  truffle.js
  yarn.lock
Labels: maintenance, ready-for-review

#644 Reputation Voting
  contracts/colony/Colony.sol
  contracts/colony/ColonyDataTypes.sol
  contracts/colony/ColonyExpenditure.sol
  contracts/colony/ColonyFunding.sol
  contracts/colony/IColony.sol
  contracts/extensions/VotingReputation.sol
  contracts/extensions/VotingReputationFactory.sol
  docs/_Interface_IColony.md
  helpers/task-review-signing.js
  helpers/test-helper.js
  scripts/check-recovery.js
  scripts/check-storage.js
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony-expenditure.js
  test/extensions/voting-rep.js
Labels: under-review

#871 Fix spelling error(s?)
  contracts/colony/ColonyDataTypes.sol
  docs/_Interface_IColony.md
Labels: maintenance

#874 Add tokenLockingAddress to ColonyStorage
  contracts/colony/Colony.sol
  contracts/colony/ColonyFunding.sol
  contracts/colony/ColonyStorage.sol
  test-smoke/colony-storage-consistent.js
Labels: under-review

#714 Extension Manager
  contracts/colony/Colony.sol
  contracts/colony/ColonyAuthority.sol
  contracts/colony/ColonyDataTypes.sol
  contracts/colony/ColonyRoles.sol
  contracts/colony/IColony.sol
  contracts/colony/IMetaColony.sol
  contracts/colonyNetwork/ColonyNetwork.sol
  contracts/colonyNetwork/ColonyNetworkDataTypes.sol
  contracts/colonyNetwork/ColonyNetworkExtensions.sol
  contracts/colonyNetwork/ColonyNetworkStorage.sol
  contracts/colonyNetwork/IColonyNetwork.sol
  contracts/extensions/CoinMachine.sol
  contracts/extensions/CoinMachineFactory.sol
  contracts/extensions/ColonyExtension.sol
  contracts/extensions/FundingQueue.sol
  contracts/extensions/FundingQueueFactory.sol
  contracts/extensions/OneTxPayment.sol
  contracts/extensions/OneTxPaymentFactory.sol
  contracts/extensions/VotingReputation.sol
  contracts/extensions/VotingReputationFactory.sol
  contracts/testHelpers/TestExtensions.sol
  contracts/testHelpers/TransferTest.sol
  docs/_Docs_Extensions.md
  docs/_Docs_Overview.md
  docs/_Interface_IColony.md
  docs/_Interface_IColonyNetwork.md
  docs/_Interface_IMetaColony.md
  helpers/test-data-generator.js
  helpers/test-helper.js
  helpers/upgradable-contracts.js
  migrations/2_deploy_contracts.js
  migrations/3_setup_colony_network.js
  migrations/4_setup_colony_version_resolver.js
  scripts/check-recovery.js
  scripts/check-storage.js
  test-gas-costs/gasCosts.js
  test-smoke/colony-storage-consistent.js
  test-upgrade/colony-upgrade.js
  test/contracts-network/colony-network-extensions.js
  test/contracts-network/colony-network.js
  test/contracts-network/colony-permissions.js
  test/contracts-network/colony-reward-payouts.js
  test/contracts-network/colony-token-integrations.js
  test/contracts-network/router-resolver.js
  test/extensions/coin-machine.js
  test/extensions/funding-queue.js
  test/extensions/one-tx-payment.js
  test/extensions/voting-rep.js
  test/reputation-system/happy-paths.js
  yarn.lock
Labels: under-review
