Repository JoinColony/colonyNetwork, pull requests merged in 2020-06, with the labels that each got.

#771 UINT256_MAX in Domain Proofs
  contracts/colony/Colony.sol
  contracts/colony/ColonyStorage.sol
  contracts/colonyNetwork/ColonyNetwork.sol
  contracts/extensions/FundingQueue.sol
  contracts/extensions/OneTxPayment.sol
  helpers/test-data-generator.js
  helpers/test-helper.js
  test-gas-costs/gasCosts.js
  test/contracts-network/colony-expenditure.js
  test/contracts-network/colony-funding.js
  test/contracts-network/colony-payment.js
  test/contracts-network/colony-permissions.js
  test/contracts-network/colony-recovery.js
  test/contracts-network/colony-reward-payouts.js
  test/contracts-network/colony-staking.js
  test/contracts-network/colony-task.js
  test/contracts-network/colony.js
  test/contracts-network/meta-colony.js
  test/contracts-network/reputation-update.js
  test/contracts-network/token-locking.js
  test/extensions/funding-queue.js
  test/extensions/one-tx-payment.js
  test/reputation-system/client-calculations.js
  test/reputation-system/dispute-resolution-misbehaviour.js
  test/reputation-system/disputes-over-child-reputation.js
  test/reputation-system/happy-paths.js
  test/reputation-system/root-hash-submissions.js
Labels: maintenance, ready-for-review

#849 Use payments rather than tasks in reputation tests where appropriate
  .circleci/config.yml
  test/reputation-system/dispute-resolution-misbehaviour.js
  test/reputation-system/happy-paths.js
Labels: maintenance

#845 Arbitration Reputation Penalties
  contracts/colony/Colony.sol
  contracts/colony/ColonyAuthority.sol
  contracts/colony/IColony.sol
  docs/_Interface_IColony.md
  test/contracts-network/colony-permissions.js
Labels: feature, ready-for-review

#851 Improve before(each) speed for some tests
  helpers/test-data-generator.js
  helpers/test-helper.js
  test/contracts-network/colony-recovery.js
  test/contracts-network/colony.js
  test/contracts-network/meta-colony.js
Labels: maintenance, ready-for-review

#721 Say leaves when we mean leaves
  contracts/colonyNetwork/ColonyNetwork.sol
  contracts/colonyNetwork/ColonyNetworkDataTypes.sol
  contracts/colonyNetwork/ColonyNetworkMining.sol
  contracts/colonyNetwork/ColonyNetworkStorage.sol
  contracts/colonyNetwork/IColonyNetwork.sol
  contracts/reputationMiningCycle/IReputationMiningCycle.sol
  contracts/reputationMiningCycle/ReputationMiningCycle.sol
  contracts/reputationMiningCycle/ReputationMiningCycleCommon.sol
  contracts/reputationMiningCycle/ReputationMiningCycleDataTypes.sol
  contracts/reputationMiningCycle/ReputationMiningCycleRespond.sol
  docs/_Interface_IColonyNetwork.md
  docs/_Interface_IReputationMiningCycle.md
  helpers/test-helper.js
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/ReputationMinerClient.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongJRHRightNLeaves.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongNLeaves.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongNLeaves2.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongProofLogEntry.js
  packages/reputation-miner/test/MaliciousReputationMinerWrongResponse.js
  test/contracts-network/colony-network-recovery.js
  test/reputation-system/dispute-resolution-misbehaviour.js
  test/reputation-system/reputation-mining-client/client-auto-functionality.js
  test/reputation-system/root-hash-submissions.js
  test/reputation-system/types-of-disagreement.js
Labels: maintenance, ready-for-review
