Repository JoinColony/colonyNetwork, pull requests merged in 2020-11, with the labels that each got.

#876 Add support for arbitrary transactions
  contracts/colony/Colony.sol
  contracts/colony/ColonyAuthority.sol
  contracts/colony/ColonyStorage.sol
  contracts/colony/ColonyTask.sol
  contracts/colony/IColony.sol
  contracts/colonyNetwork/ColonyNetworkExtensions.sol
  contracts/extensions/CoinMachine.sol
  contracts/extensions/ColonyExtension.sol
  contracts/extensions/FundingQueue.sol
  contracts/extensions/OneTxPayment.sol
  contracts/extensions/VotingReputation.sol
  contracts/testHelpers/TestExtensions.sol
  docs/_Interface_IColony.md
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony-network-extensions.js
  test/contracts-network/colony.js
  test/extensions/coin-machine.js
  test/extensions/funding-queue.js
  test/extensions/one-tx-payment.js
  test/extensions/voting-rep.js
Labels: ready-for-review

#892 Correctly order addresses in OneTxPayment tests
  test/extensions/one-tx-payment.js
Labels: maintenance

#893 Order addresses by total reputation in oracle endpoint
  packages/reputation-miner/ReputationMiner.js
  test/reputation-system/client-core-functionality.js
Labels: maintenance

#891 Add ExtensionInitialised events to extensions
  contracts/extensions/CoinMachine.sol
  contracts/extensions/ColonyExtension.sol
  contracts/extensions/VotingReputation.sol
  test/extensions/coin-machine.js
  test/extensions/voting-rep.js
Labels: in-progress, maintenance

#895 Add missing view to getDeprecated to indicate it is read-only
  contracts/extensions/ColonyExtension.sol
  test/extensions/coin-machine.js
  test/extensions/funding-queue.js
  test/extensions/voting-rep.js
Labels: ready-for-review

#896 Test CoinMachine works if token is locked
  test/extensions/coin-machine.js
Labels: ready-for-review

#898 Test with/without trailing slash for reputation oracle endpoint
  test/reputation-system/client-core-functionality.js
Labels: ready-for-review

#900 Stop yargs converting addresses to large numbers
  packages/reputation-miner/bin/index.js
  packages/reputation-miner/package.json
Labels: ready-for-review

#901 Add needed events to recovery mode; Improve event tests
  .eslintrc
  contracts/common/ContractRecovery.sol
  contracts/common/ContractRecoveryDataTypes.sol
  helpers/test-helper.js
  package.json
  test/contracts-network/colony-network.js
  test/contracts-network/colony-recovery.js
  test/contracts-network/colony-task-work-rating.js
  test/contracts-network/colony-task.js
  test/extensions/coin-machine.js
  test/extensions/voting-rep.js
Labels: ready-for-review

#902 Bump colony contract version number
  contracts/colony/Colony.sol
  helpers/constants.js
  test-gas-costs/gasCosts.js
  test-smoke/colony-storage-consistent.js
  yarn.lock
Labels: maintenance, under-review

#875 Add TokenSupplier
  contracts/extensions/CoinMachine.sol
  contracts/extensions/ColonyExtension.sol
  contracts/extensions/FundingQueue.sol
  contracts/extensions/OneTxPayment.sol
  contracts/extensions/TokenSupplier.sol
  contracts/extensions/VotingReputation.sol
  contracts/testHelpers/RequireExecuteCall.sol
  contracts/testHelpers/TestExtensions.sol
  scripts/check-recovery.js
  scripts/check-storage.js
  test/extensions/coin-machine.js
  test/extensions/token-supplier.js
  test/extensions/voting-rep.js
Labels: under-review
