Repository JoinColony/colonyNetwork, pull requests merged in 2021-07, with the labels that each got.

#972 Bumps / cleanups / updates for next release
  contracts/colony/Colony.sol
  contracts/colony/ColonyAuthority.sol
  helpers/constants.js
  scripts/deployUnmockedColonyVersions.js
  test-smoke/colony-storage-consistent.js
Labels: maintenance, ready-for-review

#973 Mining client updates due to the real world
  packages/reputation-miner/ReputationMinerClient.js
  packages/reputation-miner/bin/index.js
Labels: maintenance, ready-for-review

#970 Four minor changes
  contracts/colony/Colony.sol
  contracts/colony/ColonyAuthority.sol
  contracts/colony/IColony.sol
  contracts/extensions/VotingReputation.sol
  contracts/tokenLocking/TokenLocking.sol
  contracts/tokenLocking/TokenLockingDataTypes.sol
  docs/_Interface_IColony.md
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony-arbitrary-transactions.js
  test/contracts-network/colony-staking.js
  test/extensions/voting-rep.js
Labels: feature, maintenance, ready-for-review

#951 Add setDefaultGlobalClaimDelay for Expenditures
  contracts/colony/Colony.sol
  contracts/colony/ColonyAuthority.sol
  contracts/colony/ColonyDataTypes.sol
  contracts/colony/ColonyExpenditure.sol
  contracts/colony/ColonyStorage.sol
  contracts/colony/IColony.sol
  docs/_Interface_IColony.md
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony-expenditure.js
Labels: ready-for-review

#975 Only bring up oracle once initialisation complete
  packages/reputation-miner/ReputationMinerClient.js
Labels: maintenance, ready-for-review
