Repository JoinColony/colonyNetwork, pull requests merged in 2021-02, with the labels that each got.

#924 Add function for a colony to unlock its own token, if owner
  contracts/colony/Colony.sol
  contracts/colony/ColonyAuthority.sol
  contracts/colony/ColonyDataTypes.sol
  contracts/colony/IColony.sol
  contracts/common/ERC20Extended.sol
  helpers/test-data-generator.js
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony.js
Labels: feature, under-review

#923 Add reputation rewards
  contracts/colony/Colony.sol
  contracts/colony/ColonyAuthority.sol
  contracts/colony/ColonyFunding.sol
  contracts/colony/IColony.sol
  docs/_Interface_IColony.md
  helpers/constants.js
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony-permissions.js
Labels: ready-for-review

#922 Extension token locking
  .solcover.js
  .solcover.reputation.js
  contracts/colony/Colony.sol
  contracts/colony/ColonyFunding.sol
  contracts/colony/ColonyStorage.sol
  contracts/colony/IColony.sol
  contracts/testHelpers/RequireExecuteCall.sol
  contracts/testHelpers/TestExtensions.sol
  contracts/tokenLocking/TokenLocking.sol
  contracts/tokenLocking/TokenLockingDataTypes.sol
  contracts/tokenLocking/TokenLockingStorage.sol
  docs/_Interface_IColony.md
  helpers/test-helper.js
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony-network-extensions.js
  test/contracts-network/colony-reward-payouts.js
  test/contracts-network/colony.js
  test/contracts-network/token-locking.js
  test/extensions/token-supplier.js
Labels: ready-for-review

#907 Revisit TokenSupplier permissions
  .solcover.js
  .solcover.reputation.js
  contracts/colony/Colony.sol
  contracts/colony/ColonyAuthority.sol
  contracts/colony/IMetaColony.sol
  contracts/colonyNetwork/ColonyNetwork.sol
  contracts/colonyNetwork/ColonyNetworkStorage.sol
  contracts/colonyNetwork/IColonyNetwork.sol
  contracts/extensions/TokenSupplier.sol
  contracts/testHelpers/TestExtensions.sol
  docs/_Interface_IColonyNetwork.md
  docs/_Interface_IMetaColony.md
  migrations/9_setup_extensions.js
  test-smoke/colony-storage-consistent.js
  test/contracts-network/meta-colony.js
  test/extensions/token-supplier.js
Labels: maintenance, ready-for-review

#917 Multiple chain support
  .circleci/config.yml
  .gitignore
  .solcover.chainid.js
  contracts/colony/Colony.sol
  contracts/colonyNetwork/ColonyNetwork.sol
  contracts/colonyNetwork/ColonyNetworkENS.sol
  contracts/colonyNetwork/ColonyNetworkMining.sol
  contracts/common/MultiChain.sol
  helpers/test-helper.js
  package.json
  scripts/generate-test-contracts.sh
  scripts/start-blockchain-client.sh
  scripts/stop-blockchain-client.sh
  test-chainid/chainid-dependent-behaviour.js
  truffle.js
  yarn.lock
Labels: in-progress, ready-for-review

#908 Remove pendingBalance from TokenLocking
  .solcover.reputation.js
  contracts/colonyNetwork/ColonyNetworkMining.sol
  contracts/extensions/VotingReputation.sol
  contracts/testHelpers/ToggleableToken.sol
  contracts/tokenLocking/ITokenLocking.sol
  contracts/tokenLocking/TokenLocking.sol
  contracts/tokenLocking/TokenLockingDataTypes.sol
  docs/_Interface_ITokenLocking.md
  helpers/test-data-generator.js
  migrations/8_setup_meta_colony.js
  scripts/check-auth.js
  scripts/check-recovery.js
  scripts/check-storage.js
  test-gas-costs/gasCosts.js
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony-network-extensions.js
  test/contracts-network/colony-reward-payouts.js
  test/contracts-network/colony-staking.js
  test/contracts-network/reputation-basic-functionality.js
  test/contracts-network/token-locking.js
  test/extensions/funding-queue.js
  test/extensions/voting-rep.js
Labels: in-progress, maintenance

#925 Do not burn CLNY on Xdai during mining
  contracts/colonyNetwork/ColonyNetworkMining.sol
  helpers/test-helper.js
  test-chainid/chainid-dependent-behaviour.js
Labels: feature, ready-for-review

#927 Fix first issues arising from actual use
  contracts/colony/Colony.sol
  contracts/colony/ColonyRoles.sol
  helpers/constants.js
  scripts/deployUnmockedColonyVersions.js
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony-network.js
  test/contracts-network/colony-permissions.js
Labels: ready-for-review

#930 Minor real-world based changed to reputation miner
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/ReputationMinerClient.js
Labels: ready-for-review
