Repository JoinColony/colonyNetwork, pull requests merged in 2021-04, with the labels that each got.

#942 Only use required stake in migration
  helpers/test-helper.js
  migrations/8_setup_meta_colony.js
  test-smoke/colony-storage-consistent.js
  test/reputation-system/client-sync-functionality.js
Labels: under-review

#929 Fix slither for extensions
  contracts/extensions/CoinMachine.sol
  contracts/extensions/FundingQueue.sol
  contracts/extensions/TokenSupplier.sol
  contracts/extensions/VotingReputation.sol
  package.json
  scripts/deployOldExtensionVersions.js
  scripts/deployUnmockedColonyVersions.js
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony-arbitrary-transactions.js
  test/extensions/coin-machine.js
  test/extensions/token-supplier.js
  test/extensions/voting-rep.js
  yarn.lock
Labels: in-progress, maintenance

#931 Coin Machine v2 & Whitelist v1
  contracts/extensions/CoinMachine.sol
  contracts/extensions/Whitelist.sol
  helpers/constants.js
  helpers/test-helper.js
  migrations/9_setup_extensions.js
  scripts/check-recovery.js
  scripts/check-storage.js
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony-arbitrary-transactions.js
  test/extensions/coin-machine.js
  test/extensions/whitelist.js
Labels: feature, ready-for-review

#947 Make getStakerReward behaviour consistent
  contracts/extensions/VotingReputation.sol
  test/extensions/voting-rep.js
Labels: ready-for-review
