Repository JoinColony/colonyNetwork, pull requests merged in 2021-06, with the labels that each got.

#963 Break up test suite further for CircleCI
  .circleci/config.yml
  .gitignore
  .solcover.extensions.js
  package.json
  scripts/start-blockchain-client.sh
Labels: maintenance, ready-for-review

#964 Bump version on OneTxPayment
  contracts/extensions/OneTxPayment.sol
  test-smoke/colony-storage-consistent.js
  test/extensions/one-tx-payment.js
Labels: maintenance, ready-for-review

#966 Increase flexability miner shows towards mining cycle duration
  contracts/reputationMiningCycle/ReputationMiningCycleCommon.sol
  contracts/reputationMiningCycle/ReputationMiningCycleRespond.sol
  helpers/constants.js
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/ReputationMinerClient.js
Labels: feature, ready-for-review

#969 Allow motion stakes to be claimed even if no reward coming
  contracts/extensions/VotingReputation.sol
  test/extensions/voting-rep.js
Labels: feature, ready-for-review

#960 Per-user Coin Machine limits
  contracts/extensions/CoinMachine.sol
  contracts/extensions/ColonyExtension.sol
  contracts/extensions/FundingQueue.sol
  contracts/extensions/OneTxPayment.sol
  contracts/extensions/VotingReputation.sol
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony-arbitrary-transactions.js
  test/extensions/coin-machine.js
Labels: under-review
