Repository JoinColony/colonyNetwork, pull requests merged in 2021-03, with the labels that each got.

#926 Fix slither for main contracts
  .circleci/config.yml
  contracts/colony/Colony.sol
  contracts/colony/ColonyAuthority.sol
  contracts/colony/ColonyFunding.sol
  contracts/colony/ColonyStorage.sol
  contracts/colony/ColonyTask.sol
  contracts/colonyNetwork/ColonyNetwork.sol
  contracts/colonyNetwork/ColonyNetworkAuction.sol
  contracts/colonyNetwork/ColonyNetworkDataTypes.sol
  contracts/colonyNetwork/ColonyNetworkENS.sol
  contracts/colonyNetwork/ColonyNetworkMining.sol
  contracts/common/ContractRecovery.sol
  contracts/common/EtherRouter.sol
  contracts/reputationMiningCycle/ReputationMiningCycle.sol
  contracts/tokenLocking/TokenLocking.sol
  package.json
  slither.db.json
  test/contracts-network/colony-network.js
  test/contracts-network/colony.js
  test/contracts-network/reputation-basic-functionality.js
  test/contracts-network/token-locking.js
Labels: maintenance, ready-for-review

#935 Remove extension ordering requirement
  .solcover.js
  .solcover.reputation.js
  contracts/colony/Colony.sol
  contracts/colonyNetwork/ColonyNetworkExtensions.sol
  helpers/constants.js
  scripts/deployUnmockedColonyVersions.js
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony-network-extensions.js
Labels: maintenance, under-review

#936 Fix bug in reputation mining around the zero address
  contracts/colonyNetwork/ColonyNetwork.sol
  test/contracts-network/reputation-update.js
Labels: under-review

#938 Add new convenience functionality to the miner
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/ReputationMinerClient.js
  packages/reputation-miner/adapters/console.js
  packages/reputation-miner/bin/index.js
Labels: maintenance, ready-for-review

#939 Slight mining improvement and bootstrap correction
  contracts/colony/ColonyStorage.sol
  contracts/colonyNetwork/ColonyNetworkMining.sol
  helpers/test-helper.js
  test-chainid/chainid-dependent-behaviour.js
  test/contracts-network/colony.js
Labels: maintenance, under-review

#932 First pass at allowing arbitrary approve transactions
  contracts/colony/Colony.sol
  contracts/colony/ColonyFunding.sol
  contracts/colony/ColonyStorage.sol
  contracts/colony/IColony.sol
  docs/_Interface_IColony.md
  package.json
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony-arbitrary-transactions.js
  test/contracts-network/colony.js
Labels: feature, under-review
