Repository JoinColony/colonyNetwork, pull requests merged in 2022-04, with the labels that each got.

#1030 Adjust mining window behaviour
  contracts/reputationMiningCycle/ReputationMiningCycle.sol
  contracts/reputationMiningCycle/ReputationMiningCycleCommon.sol
  helpers/constants.js
  helpers/test-helper.js
  packages/reputation-miner/ReputationMinerClient.js
  test-chainid/chainid-dependent-behaviour.js
  test-gas-costs/gasCosts.js
  test/contracts-network/reputation-basic-functionality.js
  test/extensions/funding-queue.js
  test/extensions/voting-rep.js
  test/reputation-system/dispute-resolution-misbehaviour.js
  test/reputation-system/disputes-over-child-reputation.js
  test/reputation-system/happy-paths.js
  test/reputation-system/reputation-mining-client/client-auto-functionality.js
  test/reputation-system/root-hash-submissions.js
  test/reputation-system/types-of-disagreement.js
Labels: under-review

#986 Add support for local skills
  contracts/colony/Colony.sol
  contracts/colony/ColonyAuthority.sol
  contracts/colony/ColonyDataTypes.sol
  contracts/colony/ColonyDomains.sol
  contracts/colony/ColonyExpenditure.sol
  contracts/colony/ColonyPayment.sol
  contracts/colony/ColonyStorage.sol
  contracts/colony/ColonyTask.sol
  contracts/colony/IColony.sol
  contracts/colonyNetwork/ColonyNetwork.sol
  contracts/colonyNetwork/ColonyNetworkDeployer.sol
  contracts/colonyNetwork/ColonyNetworkStorage.sol
  contracts/colonyNetwork/IColonyNetwork.sol
  contracts/testHelpers/NoLimitSubdomains.sol
  docs/_Interface_IColony.md
  docs/_Interface_IColonyNetwork.md
  helpers/constants.js
  helpers/test-data-generator.js
  helpers/test-helper.js
  helpers/upgradable-contracts.js
  migrations/2_deploy_contracts.js
  migrations/3_setup_colony_network.js
  migrations/4_setup_colony_version_resolver.js
  migrations/8_setup_meta_colony.js
  test-gas-costs/gasCosts.js
  test-smoke/colony-storage-consistent.js
  test-upgrade/colony-upgrade.js
  test/contracts-network/colony-expenditure.js
  test/contracts-network/colony-network.js
  test/contracts-network/colony-payment.js
  test/contracts-network/colony-permissions.js
  test/contracts-network/colony-recovery.js
  test/contracts-network/colony-task.js
  test/contracts-network/colony.js
  test/contracts-network/meta-colony.js
  test/contracts-network/reputation-update.js
  test/contracts-network/router-resolver.js
  test/extensions/one-tx-payment.js
  test/reputation-system/client-calculations.js
  test/reputation-system/client-core-functionality.js
  test/reputation-system/happy-paths.js
  test/reputation-system/root-hash-submissions.js
  test/reputation-system/types-of-disagreement.js
Labels: ready-for-review

#1022 Two new events to support frontend
  contracts/colony/Colony.sol
  contracts/colony/ColonyDataTypes.sol
  contracts/extensions/CoinMachine.sol
Labels: maintenance, in-progress

#1033 Add MetadataDelta event and function
  contracts/colony/Colony.sol
  contracts/colony/ColonyAuthority.sol
  contracts/colony/ColonyDataTypes.sol
  contracts/colony/IColony.sol
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony.js
Labels: feature, ready-for-review

#976 Add metatransaction broadcast service
  .gitignore
  contracts/testHelpers/GasGuzzler.sol
  package.json
  packages/kyc-oracle/KycOracle.js
  packages/kyc-oracle/bin/index.js
  packages/metatransaction-broadcaster/MetatransactionBroadcaster.js
  packages/metatransaction-broadcaster/bin/index.js
  packages/metatransaction-broadcaster/package-lock.json
  packages/metatransaction-broadcaster/package.json
  packages/package-utils/TruffleLoader.js
  packages/package-utils/adapters/console.js
  packages/package-utils/adapters/discord.js
  packages/package-utils/adapters/slack.js
  packages/package-utils/colonyIOCors.js
  packages/package-utils/index.js
  packages/package-utils/package.json
  packages/package-utils/updateGasEstimate.js
  packages/reputation-miner/ReputationMinerClient.js
  packages/reputation-miner/TruffleLoader.js
  packages/reputation-miner/adapters/console.js
  packages/reputation-miner/adapters/discord.js
  packages/reputation-miner/adapters/slack.js
  packages/reputation-miner/bin/index.js
  packages/reputation-miner/patricia-test.js
  scripts/check-recovery.js
  scripts/check-storage.js
  test-gas-costs/gasCosts.js
  test-system/end-to-end.js
  test/contracts-network/colony-network-recovery.js
  test/contracts-network/colony-reward-payouts.js
  test/contracts-network/token-locking.js
  test/packages/metaTransactionBroadcaster.js
  test/reputation-system/client-calculations.js
  test/reputation-system/client-core-functionality.js
  test/reputation-system/client-sync-functionality.js
  test/reputation-system/dispute-resolution-misbehaviour.js
  test/reputation-system/disputes-over-child-reputation.js
  test/reputation-system/happy-paths.js
  test/reputation-system/reputation-mining-client/client-auto-functionality.js
  test/reputation-system/root-hash-submissions.js
  test/reputation-system/types-of-disagreement.js
  yarn.lock
Labels: feature, under-review

#1037 Add dev script to easily start reputation oracle
  package.json
  scripts/start-reputation-oracle.js
Labels: maintenance, ready-for-review
