Repository JoinColony/colonyNetwork, pull requests merged in 2022-02, with the labels that each got.

#1011 Delegated mining
  contracts/colonyNetwork/ColonyNetworkMining.sol
  contracts/colonyNetwork/ColonyNetworkStorage.sol
  contracts/colonyNetwork/IColonyNetwork.sol
  contracts/reputationMiningCycle/ReputationMiningCycle.sol
  contracts/reputationMiningCycle/ReputationMiningCycleBinarySearch.sol
  contracts/reputationMiningCycle/ReputationMiningCycleCommon.sol
  contracts/reputationMiningCycle/ReputationMiningCycleRespond.sol
  docs/_Interface_IColonyNetwork.md
  helpers/test-helper.js
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/ReputationMinerClient.js
  packages/reputation-miner/test/ReputationMinerTestWrapper.js
  test-chainid/chainid-dependent-behaviour.js
  test-gas-costs/gasCosts.js
  test-smoke/colony-storage-consistent.js
  test/contracts-network/reputation-basic-functionality.js
  test/extensions/funding-queue.js
  test/extensions/voting-rep.js
  test/reputation-system/dispute-resolution-misbehaviour.js
  test/reputation-system/disputes-over-child-reputation.js
  test/reputation-system/happy-paths.js
  test/reputation-system/root-hash-submissions.js
  test/reputation-system/types-of-disagreement.js
Labels: feature, in-progress

#1016 Fix bookkeeping and querying around mining stakes
  contracts/colonyNetwork/ColonyNetworkMining.sol
  contracts/reputationMiningCycle/ReputationMiningCycle.sol
  contracts/reputationMiningCycle/ReputationMiningCycleCommon.sol
  packages/reputation-miner/ReputationMinerClient.js
  test/reputation-system/root-hash-submissions.js
Labels: bug, ready-for-review

#1015 Miner (hopefully) faster sync, faster startup if submission made
  .gitignore
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/ReputationMinerClient.js
  packages/reputation-miner/bin/index.js
  test/reputation-system/reputation-mining-client/client-auto-functionality.js
Labels: feature, maintenance, under-review

#1020 Merge master back in to develop
  contracts/colonyNetwork/ColonyNetworkMining.sol
  contracts/colonyNetwork/ColonyNetworkStorage.sol
  contracts/colonyNetwork/IColonyNetwork.sol
  contracts/extensions/CoinMachine.sol
  contracts/reputationMiningCycle/ReputationMiningCycle.sol
  contracts/reputationMiningCycle/ReputationMiningCycleBinarySearch.sol
  contracts/reputationMiningCycle/ReputationMiningCycleCommon.sol
  contracts/reputationMiningCycle/ReputationMiningCycleRespond.sol
  contracts/tokenLocking/TokenLocking.sol
  docs/_Interface_IColonyNetwork.md
  helpers/test-helper.js
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/ReputationMinerClient.js
  packages/reputation-miner/test/ReputationMinerTestWrapper.js
  test-chainid/chainid-dependent-behaviour.js
  test-gas-costs/gasCosts.js
  test-smoke/colony-storage-consistent.js
  test/contracts-network/reputation-basic-functionality.js
  test/extensions/funding-queue.js
  test/extensions/voting-rep.js
  test/reputation-system/dispute-resolution-misbehaviour.js
  test/reputation-system/disputes-over-child-reputation.js
  test/reputation-system/happy-paths.js
  test/reputation-system/root-hash-submissions.js
  test/reputation-system/types-of-disagreement.js
Labels: ready-for-review

#1021 Fix further wrinkles in the mining client
  contracts/extensions/CoinMachine.sol
  helpers/test-helper.js
  packages/reputation-miner/ReputationMiner.js
  packages/reputation-miner/ReputationMinerClient.js
  test-smoke/colony-storage-consistent.js
  test/reputation-system/reputation-mining-client/client-auto-functionality.js
Labels: ready-for-review

#1023 Upgrade apicache to v1.6.3
  packages/reputation-miner/package.json
  yarn.lock
Labels: maintenance
