Repository JoinColony/colonyNetwork, pull requests merged in 2022-10, with the labels that each got.

#1090 Enable 'No action' (simple decicion) motions in subdomains
  .solcover.js
  .solcover.upgrade.js
  contracts/extensions/votingReputation/VotingReputation.sol
  test-smoke/colony-storage-consistent.js
  test-upgrade/voting-reputation-misalignment-upgrade.js
  test/extensions/voting-rep.js
Labels: bug, maintenance, ready-for-review

#1093 Exclude new mostly inappropriate slither detectors
  contracts/colony/ColonyFunding.sol
  contracts/extensions/CoinMachine.sol
  package.json
  slither.config.json
Labels: ready-for-review

#1088 Add even more extension docs
  contracts/extensions/EvaluatedExpenditure.sol
  contracts/extensions/FundingQueue.sol
  contracts/extensions/StakedExpenditure.sol
  contracts/extensions/StreamingPayments.sol
  contracts/extensions/TokenSupplier.sol
  docs/.templates/evaluatedexpenditure.md
  docs/.templates/fundingqueue.md
  docs/.templates/icolony.md
  docs/.templates/icolonynetwork.md
  docs/.templates/ietherrouter.md
  docs/.templates/imetacolony.md
  docs/.templates/irecovery.md
  docs/.templates/ireputationminingcycle.md
  docs/.templates/itokenlocking.md
  docs/.templates/onetxpayment.md
  docs/.templates/stakedexpenditure.md
  docs/.templates/streamingpayments.md
  docs/.templates/tokensupplier.md
  docs/index.md
  docs/interfaces/extensions/coinmachine.md
  docs/interfaces/extensions/evaluatedexpenditure.md
  docs/interfaces/extensions/fundingqueue.md
  docs/interfaces/extensions/index.md
  docs/interfaces/extensions/onetxpayment.md
  docs/interfaces/extensions/stakedexpenditure.md
  docs/interfaces/extensions/streamingpayments.md
  docs/interfaces/extensions/tokensupplier.md
  docs/interfaces/extensions/votingreputation.md
  docs/interfaces/extensions/whitelist.md
  docs/interfaces/icolony.md
  docs/interfaces/icolonynetwork.md
  docs/interfaces/ietherrouter.md
  docs/interfaces/imetacolony.md
  docs/interfaces/irecovery.md
  docs/interfaces/ireputationminingcycle.md
  docs/interfaces/itokenlocking.md
  docs/tldr/domains-skills.md
  docs/tldr/metacolony.md
  docs/tldr/pots.md
  docs/tldr/tasks.md
  scripts/docgen.js
Labels: ready-for-review

#1094 Fix incorrect refactor of checkErrorRevert
  helpers/test-helper.js
  test/extensions/staked-expenditure.js
Labels: bug

#1096 Fix streaming payment extension
  contracts/extensions/StreamingPayments.sol
  test/extensions/streaming-payments.js
Labels: bug, ready-for-review
