Repository JoinColony/colonyNetwork, pull requests merged in 2022-08, with the labels that each got.

#1075 Remove ganache-core
  package.json
  test-smoke/colony-storage-consistent.js
  truffle.js
  yarn.lock
Labels: maintenance, ready-for-review

#1071 Add support for decisions that take no action
  contracts/extensions/VotingReputation.sol
  test-smoke/colony-storage-consistent.js
  test/extensions/voting-rep.js
Labels: feature, ready-for-review

#1045 Expenditures extension, utilities, updates
  contracts/colony/Colony.sol
  contracts/colony/ColonyAuthority.sol
  contracts/colony/ColonyDataTypes.sol
  contracts/colony/ColonyExpenditure.sol
  contracts/colony/ColonyFunding.sol
  contracts/colony/ColonyRewards.sol
  contracts/colony/ColonyStorage.sol
  contracts/colony/IColony.sol
  contracts/extensions/StakedExpenditure.sol
  contracts/extensions/VotingReputation.sol
  docs/_Interface_IColony.md
  migrations/9_setup_extensions.js
  scripts/check-recovery.js
  scripts/check-storage.js
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony-expenditure.js
  test/contracts-network/colony-funding.js
  test/contracts-network/colony-permissions.js
  test/contracts-network/colony-recovery.js
  test/contracts-network/colony-staking.js
  test/extensions/evaluated-expenditure.js
  test/extensions/staked-expenditure.js
  test/extensions/voting-rep.js
  truffle.js
  yarn.lock
Labels: ready-for-review

#1072 Make the metatransaction broadcaster more robust
  packages/metatransaction-broadcaster/Dockerfile
  packages/metatransaction-broadcaster/ExtendedNonceManager.js
  packages/metatransaction-broadcaster/MetatransactionBroadcaster.js
  packages/metatransaction-broadcaster/package.json
  packages/reputation-miner/Dockerfile
  test/extensions/voting-rep.js
  test/packages/metaTransactionBroadcaster.js
  yarn.lock
Labels: feature, ready-for-review

#1077 Make miner slightly more cautious about state
  helpers/test-helper.js
  packages/reputation-miner/ReputationMinerClient.js
  packages/reputation-miner/test/ReputationMinerLongTransactionMined.js
  test/reputation-system/reputation-mining-client/client-auto-functionality.js
Labels: maintenance, ready-for-review
