Repository JoinColony/colonyNetwork, pull requests merged in 2023-08, with the labels that each got.

#1153 Fix Metatransaction broadcaster timeouts
  .circleci/config.yml
  package.json
  packages/metatransaction-broadcaster/Dockerfile
  packages/metatransaction-broadcaster/MetatransactionBroadcaster.js
Labels: bug, ready-for-review

#1114 Add reputation mining guide from gitbook
  docs/guides/reputation-mining-client.md
  docs/guides/reputation-mining.md
Labels: in-progress

#1154 Fix setExpenditurePayouts logic
  contracts/colony/ColonyFunding.sol
  test/contracts-network/colony-expenditure.js
Labels: bug, ready-for-review

#1155 Make initialise consistent on extensions
  contracts/extensions/StakedExpenditure.sol
  docs/interfaces/extensions/stakedexpenditure.md
  test-smoke/colony-storage-consistent.js
  test/extensions/staked-expenditure.js
Labels: ready-for-review

#1156 Try and fix flickery race-condition miner test
  hardhat.config.js
  helpers/test-helper.js
  package-lock.json
  package.json
  scripts/start-blockchain-client.sh
  test/reputation-system/reputation-mining-client/client-auto-functionality.js
Labels: maintenance, ready-for-review

#1141 Staged expenditure standalone extension
  contracts/extensions/StagedExpenditure.sol
  migrations/9_setup_extensions.js
  package-lock.json
  scripts/check-recovery.js
  scripts/check-storage.js
  test-smoke/colony-storage-consistent.js
  test/extensions/staged-expenditure.js
Labels: ready-to-merge

#1159 Fix flickery test when run with other tests
  packages/reputation-miner/ReputationMinerClient.js
  test/reputation-system/reputation-mining-client/client-auto-functionality.js
Labels: bug, maintenance
