Repository JoinColony/colonyNetwork, pull requests merged in 2024-07, with the labels that each got.

#1270 Introduce hardhat_setStorageAt
  helpers/test-helper.js
  scripts/deployOldUpgradeableVersion.js
  test-smoke/colony-storage-consistent.js
  test-upgrade/colony-upgrade.js
  test/contracts-network/colony-network-auction.js
  test/contracts-network/colony-network-recovery.js
  test/contracts-network/colony-network.js
Labels: ready-for-review

#1276 Bump package versions
  package.json
  pnpm-lock.yaml
Labels: ready-for-review

#1275 Add a function to deploy IMWSS
  scripts/deployOldUpgradeableVersion.js
  scripts/setupOldUpgradeableVersionHardhat.js
Labels: maintenance, ready-for-review

#1267 Remove redundant scripts
  .circleci/config.yml
  .solcover.extensions.js
  .solcover.reputation.js
  .solcover/chainid.js
  .solcover/crosschain.js
  .solcover/extensions.js
  .solcover/reputation.js
  .solcover/solcover.js
  .solcover/upgrade.js
  helpers/task-review-signing.js
  migrations/1_initial_migration.js
  migrations/2_deploy_contracts.js
  migrations/3_setup_colony_network.js
  migrations/4_setup_colony_version_resolver.js
  migrations/5_setup_token_locking.js
  migrations/6_setup_mining_cycle_resolver.js
  migrations/7_setup_ens_registry.js
  migrations/8_setup_meta_colony.js
  migrations/9_setup_extensions.js
  package.json
  scripts/deployOldExtensionVersions.js
  scripts/deployUnmockedColonyVersions.js
  scripts/process-truffle-security.js
  scripts/provision-safe-contracts.sh
  scripts/provision-token-contracts.sh
  scripts/resetParity.sh
  test-smoke/colony-storage-consistent.js
  test/contracts-network/colony-task-work-rating.js
  test/contracts-network/colony-task.js
  test/misc/chainid.js
  test/misc/end-to-end.js
  test/misc/gas-costs.js
  test/upgrade/colony-network-upgrade.js
  test/upgrade/colony-upgrade.js
  test/upgrade/reputation-mining-cycle-upgrade.js
Labels: ready-for-review

#1277 Add a script to deploy 'next' version of colony
  scripts/deployOldUpgradeableVersion.js
Labels: under-review

#1278 Fix version check script
  contracts/extensions/votingReputation/VotingReputationStorage.sol
  helpers/test-helper.js
  scripts/versioningCheck.sh
  test/extensions/voting-rep.js
Labels: under-review
